export type CollaborationProfile = "solo" | "contributor" | "team";

export const COLLABORATION_PROFILES: readonly CollaborationProfile[] = [
  "solo",
  "contributor",
  "team",
];

export function isCollaborationProfile(value: string): value is CollaborationProfile {
  return (COLLABORATION_PROFILES as readonly string[]).includes(value);
}

export function renderReviewPolicyBaseline(profile: CollaborationProfile): string {
  return [
    "# Review Policy - generated by ai-guidelines.",
    "# Collaboration profiles govern native GitHub review/merge expectations.",
    "# Semantic reviews remain governed separately by review_requirements.",
    `active_profile: ${profile}`,
    "profiles:",
    "  solo:",
    "    implementation_pr:",
    "      required_native_approvals: 0",
    "    integration_pr:",
    "      required_native_approvals: 0",
    "    accepted_findings:",
    "      require_resolution: false",
    "      require_verification_event_for_fixed: false",
    "    github:",
    "      minimum_approving_reviews: 1",
    "      require_code_owner_review: true",
    "      dismiss_stale_reviews_on_push: true",
    "      require_last_push_approval: false",
    "",
    "  contributor:",
    "    implementation_pr:",
    "      required_native_approvals: 0",
    "    integration_pr:",
    "      required_native_approvals: 1",
    "    accepted_findings:",
    "      require_resolution: true",
    "      require_verification_event_for_fixed: true",
    "    github:",
    "      minimum_approving_reviews: 1",
    "      require_code_owner_review: true",
    "      dismiss_stale_reviews_on_push: true",
    "      require_last_push_approval: false",
    "",
    "  team:",
    "    implementation_pr:",
    "      required_native_approvals: 1",
    "    integration_pr:",
    "      required_native_approvals: 2",
    "    accepted_findings:",
    "      require_resolution: true",
    "      require_verification_event_for_fixed: true",
    "    github:",
    "      minimum_approving_reviews: 2",
    "      require_code_owner_review: true",
    "      dismiss_stale_reviews_on_push: true",
    "      require_last_push_approval: true",
    "",
    "review_requirements:",
    "  defaults:",
    "    technical_audit: optional",
    "    architectural_review: optional",
    "",
  ].join("\n");
}

export function updateReviewPolicyProfileContent(
  current: string | null,
  profile: CollaborationProfile
): string {
  if (current === null) {
    return renderReviewPolicyBaseline(profile);
  }

  if (!declaresCollaborationProfile(current, profile)) {
    throw new Error(
      `Perfil de colaboração "${profile}" não declarado em .governance/review-policy.yml. ` +
        "Adicione o perfil à política ou gere uma baseline nova com init/adopt."
    );
  }

  if (!/^active_profile:\s*\S+\s*$/m.test(current)) {
    throw new Error(
      "Não encontrei active_profile em .governance/review-policy.yml. " +
        "Atualização conservadora bloqueada para não sobrescrever política customizada."
    );
  }

  return current.replace(/^active_profile:\s*\S+\s*$/m, `active_profile: ${profile}`);
}

function declaresCollaborationProfile(content: string, profile: CollaborationProfile): boolean {
  const pattern = new RegExp(`^\\s{2}${profile}:\\s*$`, "m");
  return pattern.test(content);
}
