// graph.js — GERADO por _tools/build-graph.mjs a partir de acme/ + model.yml — NÃO editar à mão.
window.GRAPH = {
  contentHash: "5b73796c7bac",
  company: "acme",
  profileDeclaration: {
    scope: "acme (a org inteira)",
    profile: "full",
    eligibility:
      "papéis separados existem: sponsor · PM/liderança por área · eng por time · dados · SRE",
    "approved-by": "sponsor-acme",
    ttl: "2027-06-30",
    "review-at": "2027-01-15",
    badge:
      "perfil full — SoD completo; mutações ruler-authority são soft-mandatory (par OU break-glass logado)",
  },
  nodes: [
    {
      id: "obj-revenue",
      type: "objective",
      label: "crescer receita via cross-sell",
      data: {
        id: "obj-revenue",
        level: "company",
        title: "crescer receita via cross-sell",
        period: "2027",
        owner: "sponsor-acme",
        status: "active",
      },
    },
    {
      id: "obj-efficiency",
      type: "objective",
      label: "reduzir o custo de servir",
      data: {
        id: "obj-efficiency",
        level: "company",
        title: "reduzir o custo de servir",
        period: "2027",
        owner: "sponsor-acme",
        status: "active",
      },
    },
    {
      id: "obj-retention",
      type: "objective",
      label: "reter clientes (derrubar o churn)",
      data: {
        id: "obj-retention",
        level: "company",
        title: "reter clientes (derrubar o churn)",
        period: "2027",
        owner: "sponsor-acme",
        status: "active",
      },
    },
    {
      id: "obj-trust",
      type: "objective",
      label: "confiança: privacidade e conformidade por padrão",
      data: {
        id: "obj-trust",
        level: "company",
        title: "confiança: privacidade e conformidade por padrão",
        period: "2027",
        owner: "sponsor-acme",
        status: "active",
      },
    },
    {
      id: "area-growth",
      type: "area",
      label: "área de growth",
      data: {
        id: "area-growth",
        title: "área de growth",
        "cascades-from": ["obj-revenue", "obj-retention"],
        driver: "cross-sell entre os produtos + ativação que retém",
        owner: "head-growth",
      },
    },
    {
      id: "area-platform",
      type: "area",
      label: "área de plataforma",
      data: {
        id: "area-platform",
        title: "área de plataforma",
        "cascades-from": ["obj-efficiency", "obj-trust"],
        driver: "eficiência, confiabilidade e privacidade da plataforma",
        owner: "head-platform",
      },
    },
    {
      id: "area-cx",
      type: "area",
      label: "área de experiência do cliente",
      data: {
        id: "area-cx",
        title: "área de experiência do cliente",
        "cascades-from": ["obj-retention", "obj-efficiency"],
        driver: "suporte que retém + autoatendimento que barateia",
        owner: "head-cx",
      },
    },
    {
      id: "tese-cross-sell",
      type: "thesis",
      label:
        "ofertar o produto B à base do produto A, evidenciando o uso conjunto, move a conversão",
      data: {
        id: "tese-cross-sell",
        frames: "obj-revenue",
        says: "ofertar o produto B à base do produto A, evidenciando o uso conjunto, move a conversão",
        owner: "head-growth",
      },
    },
    {
      id: "tese-pricing-anual",
      type: "thesis",
      label: "planos anuais com desconto aumentam a receita por cliente e antecipam caixa",
      data: {
        id: "tese-pricing-anual",
        frames: "obj-revenue",
        says: "planos anuais com desconto aumentam a receita por cliente e antecipam caixa",
        owner: "head-growth",
      },
    },
    {
      id: "tese-onboarding-retencao",
      type: "thesis",
      label: "cliente ativado na primeira semana cancela muito menos — ativação precoce é retenção",
      data: {
        id: "tese-onboarding-retencao",
        frames: "obj-retention",
        says: "cliente ativado na primeira semana cancela muito menos — ativação precoce é retenção",
        owner: "head-growth",
      },
    },
    {
      id: "tese-suporte-retencao",
      type: "thesis",
      label: "resolver rápido no suporte reduz churn — tempo de resolução prevê cancelamento",
      data: {
        id: "tese-suporte-retencao",
        frames: "obj-retention",
        says: "resolver rápido no suporte reduz churn — tempo de resolução prevê cancelamento",
        owner: "head-cx",
      },
    },
    {
      id: "tese-eficiencia",
      type: "thesis",
      label: "padronizar o stack e endurecer a plataforma derrubam o custo por pedido",
      data: {
        id: "tese-eficiencia",
        frames: "obj-efficiency",
        says: "padronizar o stack e endurecer a plataforma derrubam o custo por pedido",
        owner: "head-platform",
      },
    },
    {
      id: "tese-self-service",
      type: "thesis",
      label: "autoatendimento bem feito derruba o custo por ticket sem piorar a satisfação",
      data: {
        id: "tese-self-service",
        frames: "obj-efficiency",
        says: "autoatendimento bem feito derruba o custo por ticket sem piorar a satisfação",
        owner: "head-cx",
      },
    },
    {
      id: "tese-privacidade",
      type: "thesis",
      label: "minimizar dados coletados e dar controle ao cliente reduz risco e constrói confiança",
      data: {
        id: "tese-privacidade",
        frames: "obj-trust",
        says: "minimizar dados coletados e dar controle ao cliente reduz risco e constrói confiança",
        owner: "head-platform",
      },
    },
    {
      id: "time-billing",
      type: "team",
      label: "time-billing",
      data: {
        id: "time-billing",
        area: "area-growth",
        lead: "lead-billing",
      },
    },
    {
      id: "time-onboarding",
      type: "team",
      label: "time-onboarding",
      data: {
        id: "time-onboarding",
        area: "area-growth",
        lead: "lead-onboarding",
      },
    },
    {
      id: "time-checkout",
      type: "team",
      label: "time-checkout",
      data: {
        id: "time-checkout",
        area: "area-platform",
        lead: "lead-checkout",
      },
    },
    {
      id: "time-data",
      type: "team",
      label: "time-data",
      data: {
        id: "time-data",
        area: "area-platform",
        lead: "lead-data",
      },
    },
    {
      id: "time-sre",
      type: "team",
      label: "time-sre",
      data: {
        id: "time-sre",
        area: "area-platform",
        lead: "lead-sre",
      },
    },
    {
      id: "time-identity",
      type: "team",
      label: "time-identity",
      data: {
        id: "time-identity",
        area: "area-platform",
        lead: "lead-identity",
      },
    },
    {
      id: "time-support",
      type: "team",
      label: "time-support",
      data: {
        id: "time-support",
        area: "area-cx",
        lead: "lead-support",
      },
    },
    {
      id: "acme-mfe-billing",
      type: "repo",
      label: "acme-mfe-billing",
      data: {
        id: "acme-mfe-billing",
        owner: "time-billing",
        caps: ["billing-ui", "planos", "upgrade"],
      },
    },
    {
      id: "acme-api-billing",
      type: "repo",
      label: "acme-api-billing",
      data: {
        id: "acme-api-billing",
        owner: "time-billing",
        caps: ["cobrança", "elegibilidade", "assinaturas"],
      },
    },
    {
      id: "acme-mfe-onboarding",
      type: "repo",
      label: "acme-mfe-onboarding",
      data: {
        id: "acme-mfe-onboarding",
        owner: "time-onboarding",
        caps: ["onboarding", "ativação", "tours"],
      },
    },
    {
      id: "acme-checkout",
      type: "repo",
      label: "acme-checkout",
      data: {
        id: "acme-checkout",
        owner: "time-checkout",
        caps: ["checkout-ui", "carrinho", "cupom", "frete"],
      },
    },
    {
      id: "acme-checkout-api",
      type: "repo",
      label: "acme-checkout-api",
      data: {
        id: "acme-checkout-api",
        owner: "time-checkout",
        caps: ["pedidos", "pagamento", "frete-api"],
      },
    },
    {
      id: "acme-analytics",
      type: "repo",
      label: "acme-analytics",
      data: {
        id: "acme-analytics",
        owner: "time-data",
        caps: ["eventos", "métricas", "experimentos-fonte"],
      },
    },
    {
      id: "acme-data-pipeline",
      type: "repo",
      label: "acme-data-pipeline",
      data: {
        id: "acme-data-pipeline",
        owner: "time-data",
        caps: ["etl", "warehouse"],
      },
    },
    {
      id: "acme-obs-stack",
      type: "repo",
      label: "acme-obs-stack",
      data: {
        id: "acme-obs-stack",
        owner: "time-sre",
        caps: ["alertas", "slo", "tracing", "atesta-outcomes"],
      },
    },
    {
      id: "acme-identity",
      type: "repo",
      label: "acme-identity",
      data: {
        id: "acme-identity",
        owner: "time-identity",
        caps: ["auth", "login", "consentimento", "privacidade"],
      },
    },
    {
      id: "acme-help-center",
      type: "repo",
      label: "acme-help-center",
      data: {
        id: "acme-help-center",
        owner: "time-support",
        caps: ["ajuda", "tickets", "chatbot", "self-service"],
      },
    },
    {
      id: "acme-web-host",
      type: "repo",
      label: "acme-web-host",
      data: {
        id: "acme-web-host",
        owner: "area-platform",
        caps: ["shell-mfes", "contexto-de-usuario", "roteamento"],
        note: "compartilhado",
      },
    },
    {
      id: "acme-design-system",
      type: "repo",
      label: "acme-design-system",
      data: {
        id: "acme-design-system",
        owner: "area-platform",
        caps: ["componentes", "tokens"],
        note: "compartilhado",
      },
    },
    {
      id: "acme-core-api",
      type: "repo",
      label: "acme-core-api",
      data: {
        id: "acme-core-api",
        owner: "area-platform",
        caps: ["api-legada", "integracoes"],
        note: "MONOLITO legado — grande demais p/ um time só: donos por MÓDULO (padrão CODEOWNERS)",
        modules: [
          {
            id: "mod-billing",
            owner: "time-billing",
            caps: ["cobranca-legada", "notas-fiscais"],
          },
          {
            id: "mod-orders",
            owner: "time-checkout",
            caps: ["pedidos-legados", "estoque"],
          },
          {
            id: "mod-accounts",
            owner: "time-identity",
            caps: ["contas", "permissoes-legadas"],
          },
          {
            id: "mod-reports",
            owner: "time-data",
            caps: ["relatorios-legados"],
          },
        ],
      },
    },
    {
      id: "acme-core-api#mod-billing",
      type: "module",
      label: "mod-billing",
      data: {
        id: "mod-billing",
        owner: "time-billing",
        caps: ["cobranca-legada", "notas-fiscais"],
        repo: "acme-core-api",
      },
    },
    {
      id: "acme-core-api#mod-orders",
      type: "module",
      label: "mod-orders",
      data: {
        id: "mod-orders",
        owner: "time-checkout",
        caps: ["pedidos-legados", "estoque"],
        repo: "acme-core-api",
      },
    },
    {
      id: "acme-core-api#mod-accounts",
      type: "module",
      label: "mod-accounts",
      data: {
        id: "mod-accounts",
        owner: "time-identity",
        caps: ["contas", "permissoes-legadas"],
        repo: "acme-core-api",
      },
    },
    {
      id: "acme-core-api#mod-reports",
      type: "module",
      label: "mod-reports",
      data: {
        id: "mod-reports",
        owner: "time-data",
        caps: ["relatorios-legados"],
        repo: "acme-core-api",
      },
    },
    {
      id: "acme-user-context",
      type: "contract",
      label: "acme-user-context@v3",
      data: {
        id: "acme-user-context",
        revision: "v3",
        "owner-repo": "acme-web-host",
        consumers: ["acme-mfe-billing", "acme-mfe-onboarding", "acme-checkout"],
        "compatibility-window": null,
      },
    },
    {
      id: "acme-design-tokens",
      type: "contract",
      label: "acme-design-tokens@v2",
      data: {
        id: "acme-design-tokens",
        revision: "v2",
        "owner-repo": "acme-design-system",
        consumers: ["acme-mfe-billing", "acme-mfe-onboarding", "acme-checkout"],
        "compatibility-window": null,
      },
    },
    {
      id: "acme-events-schema",
      type: "contract",
      label: "acme-events-schema@v1",
      data: {
        id: "acme-events-schema",
        revision: "v1",
        "owner-repo": "acme-analytics",
        consumers: [
          "acme-mfe-billing",
          "acme-mfe-onboarding",
          "acme-checkout",
          "acme-checkout-api",
        ],
        "compatibility-window": null,
      },
    },
    {
      id: "conversion-rate",
      type: "metric",
      label: "conversion-rate",
      data: {
        id: "conversion-rate",
        unit: "%",
        source: "acme-analytics",
        aggregation: "avg",
        owner: "time-data",
      },
    },
    {
      id: "activation-rate",
      type: "metric",
      label: "activation-rate",
      data: {
        id: "activation-rate",
        unit: "%",
        source: "acme-analytics",
        aggregation: "avg",
        owner: "time-data",
      },
    },
    {
      id: "churn-rate",
      type: "metric",
      label: "churn-rate",
      data: {
        id: "churn-rate",
        unit: "%/mês",
        source: "acme-analytics",
        aggregation: "avg",
        owner: "time-data",
      },
    },
    {
      id: "cost-to-serve",
      type: "metric",
      label: "cost-to-serve",
      data: {
        id: "cost-to-serve",
        unit: "R$/pedido",
        source: "acme-data-pipeline",
        aggregation: "avg",
        owner: "time-data",
      },
    },
    {
      id: "ticket-cost",
      type: "metric",
      label: "ticket-cost",
      data: {
        id: "ticket-cost",
        unit: "R$/ticket",
        source: "acme-data-pipeline",
        aggregation: "avg",
        owner: "time-data",
      },
    },
    {
      id: "p99-latency",
      type: "metric",
      label: "p99-latency",
      data: {
        id: "p99-latency",
        unit: "ms",
        source: "acme-obs-stack",
        aggregation: "p99",
        owner: "time-sre",
      },
    },
    {
      id: "incident-count",
      type: "metric",
      label: "incident-count",
      data: {
        id: "incident-count",
        unit: "incidentes/mês",
        source: "acme-obs-stack",
        aggregation: "sum",
        owner: "time-sre",
      },
    },
    {
      id: "consent-coverage",
      type: "metric",
      label: "consent-coverage",
      data: {
        id: "consent-coverage",
        unit: "% de dados com base legal",
        source: "acme-data-pipeline",
        aggregation: "avg",
        owner: "time-data",
      },
    },
    {
      id: "tgt-billing-conv",
      type: "target",
      label: "+X% de conversão de cross-sell",
      data: {
        id: "tgt-billing-conv",
        node: "time-billing",
        metric: "conversion-rate",
        period: "2027-H1",
        expected: "+X% de conversão de cross-sell",
        definer: "pm-growth",
        attester: "acme-analytics",
        "contributes-to": "obj-revenue",
        status: "active",
      },
    },
    {
      id: "tgt-onboarding-act",
      type: "target",
      label: "+Y% de ativação",
      data: {
        id: "tgt-onboarding-act",
        node: "time-onboarding",
        metric: "activation-rate",
        period: "2027-H1",
        expected: "+Y% de ativação",
        definer: "pm-growth",
        attester: "acme-analytics",
        "contributes-to": "obj-revenue",
        status: "active",
      },
    },
    {
      id: "tgt-checkout-stack",
      type: "target",
      label: "checkout no stack novo até o fim do H2 (-W% de custo)",
      data: {
        id: "tgt-checkout-stack",
        node: "time-checkout",
        metric: "cost-to-serve",
        period: "2027-H2",
        expected: "checkout no stack novo até o fim do H2 (-W% de custo)",
        definer: "head-platform",
        attester: "acme-data-pipeline",
        "contributes-to": "obj-efficiency",
        status: "active",
      },
    },
    {
      id: "tgt-data-cost",
      type: "target",
      label: "-Z% no custo da infra de dados",
      data: {
        id: "tgt-data-cost",
        node: "time-data",
        metric: "cost-to-serve",
        period: "2027-H1",
        expected: "-Z% no custo da infra de dados",
        definer: "head-platform",
        attester: "acme-data-pipeline",
        "contributes-to": "obj-efficiency",
        status: "active",
      },
    },
    {
      id: "tgt-sre-p99",
      type: "target",
      label: "p99 abaixo de N ms",
      data: {
        id: "tgt-sre-p99",
        node: "time-sre",
        metric: "p99-latency",
        period: "2027-H1",
        expected: "p99 abaixo de N ms",
        definer: "head-platform",
        attester: "acme-obs-stack",
        "contributes-to": "obj-efficiency",
        status: "active",
      },
    },
    {
      id: "tgt-sre-incidents",
      type: "target",
      label: "-30% de incidentes",
      data: {
        id: "tgt-sre-incidents",
        node: "time-sre",
        metric: "incident-count",
        period: "2027-H1",
        expected: "-30% de incidentes",
        definer: "head-platform",
        attester: "acme-obs-stack",
        "contributes-to": "obj-efficiency",
        status: "active",
      },
    },
    {
      id: "tgt-checkout-conv",
      type: "target",
      label: "+V% de conversão no checkout (1 clique)",
      data: {
        id: "tgt-checkout-conv",
        node: "time-checkout",
        metric: "conversion-rate",
        period: "2027-H1",
        expected: "+V% de conversão no checkout (1 clique)",
        definer: "pm-growth",
        attester: "acme-analytics",
        "contributes-to": "obj-revenue",
        status: "active",
      },
    },
    {
      id: "tgt-onboarding-churn",
      type: "target",
      label: "-P p.p. de churn nos ativados na 1ª semana",
      data: {
        id: "tgt-onboarding-churn",
        node: "time-onboarding",
        metric: "churn-rate",
        period: "2027-H1",
        expected: "-P p.p. de churn nos ativados na 1ª semana",
        definer: "pm-growth",
        attester: "acme-analytics",
        "contributes-to": "obj-retention",
        status: "active",
      },
    },
    {
      id: "tgt-support-churn",
      type: "target",
      label: "-Q p.p. de churn entre quem abre ticket",
      data: {
        id: "tgt-support-churn",
        node: "time-support",
        metric: "churn-rate",
        period: "2027-H1",
        expected: "-Q p.p. de churn entre quem abre ticket",
        definer: "head-cx",
        attester: "acme-analytics",
        "contributes-to": "obj-retention",
        status: "active",
      },
    },
    {
      id: "tgt-support-cost",
      type: "target",
      label: "-R% no custo por ticket via autoatendimento",
      data: {
        id: "tgt-support-cost",
        node: "time-support",
        metric: "ticket-cost",
        period: "2027-H2",
        expected: "-R% no custo por ticket via autoatendimento",
        definer: "head-cx",
        attester: "acme-data-pipeline",
        "contributes-to": "obj-efficiency",
        status: "active",
      },
    },
    {
      id: "tgt-identity-consent",
      type: "target",
      label: "100% dos dados com base legal registrada",
      data: {
        id: "tgt-identity-consent",
        node: "time-identity",
        metric: "consent-coverage",
        period: "2027-H1",
        expected: "100% dos dados com base legal registrada",
        definer: "head-platform",
        attester: "acme-data-pipeline",
        "contributes-to": "obj-trust",
        status: "active",
      },
    },
    {
      id: "intent-checkout-1click",
      type: "intent",
      label: "checkout em 1 clique para clientes recorrentes",
      data: {
        id: "intent-checkout-1click",
        title: "checkout em 1 clique para clientes recorrentes",
        team: "time-checkout",
        "authorized-by": "obj-revenue",
        "primary-target": "tgt-checkout-conv",
        thesis: "tese-cross-sell",
        approach: "validate-first",
        hypothesis: "reduzir o checkout a 1 clique p/ recorrentes aumenta a conversão em V%",
        "decision-rule":
          "roda 3 semanas OU 30k exposições; ganha se conversão ↑ V% sem aumento de estorno",
        signal: "none",
        "contracts-consumed": ["acme-events-schema"],
        works: [
          {
            id: "flag-1click",
            repo: "acme-checkout",
            purpose: "create",
            desc: "fluxo de 1 clique atrás da flag (só recorrentes)",
            review: "interno",
          },
          {
            id: "api-token-pagamento",
            repo: "acme-checkout-api",
            purpose: "create",
            desc: "token de pagamento salvo p/ recorrentes",
            review: "interno",
          },
          {
            id: "baseline-1click",
            repo: "acme-analytics",
            purpose: "operate",
            desc: "eventos + baseline do funil (consome o schema existente, sem revisão)",
            review: "externo: time-data",
          },
        ],
        next: [
          {
            when: "veredito: ganhou",
            then: "graduation — 1 clique vira padrão p/ recorrentes",
            gate: "accept-verdict",
          },
          {
            when: "veredito: perdeu",
            then: "cleanup — remove a flag e o token opt-in",
            gate: "accept-verdict",
          },
          {
            when: "veredito: inconclusivo",
            then: "refina a hipótese (segmento menor) OU vira descoberta",
            gate: "accept-verdict",
          },
        ],
      },
    },
    {
      id: "intent-checkout-1click::flag-1click",
      type: "work",
      label: "flag-1click",
      data: {
        id: "flag-1click",
        repo: "acme-checkout",
        purpose: "create",
        desc: "fluxo de 1 clique atrás da flag (só recorrentes)",
        review: "interno",
        intent: "intent-checkout-1click",
      },
    },
    {
      id: "intent-checkout-1click::api-token-pagamento",
      type: "work",
      label: "api-token-pagamento",
      data: {
        id: "api-token-pagamento",
        repo: "acme-checkout-api",
        purpose: "create",
        desc: "token de pagamento salvo p/ recorrentes",
        review: "interno",
        intent: "intent-checkout-1click",
      },
    },
    {
      id: "intent-checkout-1click::baseline-1click",
      type: "work",
      label: "baseline-1click",
      data: {
        id: "baseline-1click",
        repo: "acme-analytics",
        purpose: "operate",
        desc: "eventos + baseline do funil (consome o schema existente, sem revisão)",
        review: "externo: time-data",
        intent: "intent-checkout-1click",
      },
    },
    {
      id: "intent-checkout-stack",
      type: "intent",
      label: "migrar o checkout para o stack novo",
      data: {
        id: "intent-checkout-stack",
        title: "migrar o checkout para o stack novo",
        team: "time-checkout",
        "authorized-by": "obj-efficiency",
        "primary-target": "tgt-checkout-stack",
        thesis: "tese-eficiencia",
        approach: "direct",
        signal: "touches-contract",
        "contracts-changed": ["acme-user-context"],
        works: [
          {
            id: "spike-carrinho",
            repo: "acme-checkout",
            purpose: "discover",
            desc: "EXPLORATION — como migrar o estado do carrinho sem downtime? fate informa a onda 1",
            timebox: "5d",
            review: "interno",
          },
          {
            id: "componentes-ds",
            repo: "acme-design-system",
            purpose: "create",
            desc: "componentes do checkout no stack novo (consome acme-design-tokens sem revisão)",
            review: "externo: area-platform",
          },
          {
            id: "porta-fluxo",
            repo: "acme-checkout",
            purpose: "sustain",
            desc: "porta o fluxo principal (de → para) usando os componentes novos",
            "blocked-by": ["spike-carrinho"],
            "delivery-after": ["componentes-ds"],
            review: "interno",
          },
          {
            id: "adapta-api",
            repo: "acme-checkout-api",
            purpose: "sustain",
            desc: "adapta os endpoints ao stack novo",
            review: "interno",
          },
          {
            id: "estrangula-pedidos",
            repo: "acme-core-api",
            module: "mod-orders",
            purpose: "sustain",
            desc: "estrangula o fluxo de pedidos do MONOLITO (strangler) — módulo do próprio time",
            "blocked-by": ["spike-carrinho"],
            review: "interno",
          },
          {
            id: "revisao-contrato",
            repo: "acme-web-host",
            purpose: "sustain",
            desc: "acme-user-context v3 → v4 COM QUEBRA — abre a janela; mutação compat-window-change (dangerous → alerta q/r/d)",
            review: "externo: area-platform",
          },
          {
            id: "monitor-canary",
            repo: "acme-obs-stack",
            purpose: "operate",
            desc: "monitor do canary (guardrails do corte)",
            "delivery-after": ["porta-fluxo", "adapta-api"],
            review: "externo: time-sre",
          },
        ],
        next: [
          {
            when: "onda 1 concluída",
            then: "janela ABERTA: v3 e v4 convivem; consumidores migram no seu ritmo",
          },
          {
            when: "consumidores migrados",
            then: "corte gradual — canary com plano de reversão",
            gate: "release-rollout",
          },
          {
            when: "corte completo",
            then: "fecha a janela, desliga o legado; outcome sobe no placar do custo de servir",
          },
        ],
      },
    },
    {
      id: "intent-checkout-stack::spike-carrinho",
      type: "work",
      label: "spike-carrinho",
      data: {
        id: "spike-carrinho",
        repo: "acme-checkout",
        purpose: "discover",
        desc: "EXPLORATION — como migrar o estado do carrinho sem downtime? fate informa a onda 1",
        timebox: "5d",
        review: "interno",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-checkout-stack::componentes-ds",
      type: "work",
      label: "componentes-ds",
      data: {
        id: "componentes-ds",
        repo: "acme-design-system",
        purpose: "create",
        desc: "componentes do checkout no stack novo (consome acme-design-tokens sem revisão)",
        review: "externo: area-platform",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-checkout-stack::porta-fluxo",
      type: "work",
      label: "porta-fluxo",
      data: {
        id: "porta-fluxo",
        repo: "acme-checkout",
        purpose: "sustain",
        desc: "porta o fluxo principal (de → para) usando os componentes novos",
        "blocked-by": ["spike-carrinho"],
        "delivery-after": ["componentes-ds"],
        review: "interno",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-checkout-stack::adapta-api",
      type: "work",
      label: "adapta-api",
      data: {
        id: "adapta-api",
        repo: "acme-checkout-api",
        purpose: "sustain",
        desc: "adapta os endpoints ao stack novo",
        review: "interno",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-checkout-stack::estrangula-pedidos",
      type: "work",
      label: "estrangula-pedidos",
      data: {
        id: "estrangula-pedidos",
        repo: "acme-core-api",
        module: "mod-orders",
        purpose: "sustain",
        desc: "estrangula o fluxo de pedidos do MONOLITO (strangler) — módulo do próprio time",
        "blocked-by": ["spike-carrinho"],
        review: "interno",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-checkout-stack::revisao-contrato",
      type: "work",
      label: "revisao-contrato",
      data: {
        id: "revisao-contrato",
        repo: "acme-web-host",
        purpose: "sustain",
        desc: "acme-user-context v3 → v4 COM QUEBRA — abre a janela; mutação compat-window-change (dangerous → alerta q/r/d)",
        review: "externo: area-platform",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-checkout-stack::monitor-canary",
      type: "work",
      label: "monitor-canary",
      data: {
        id: "monitor-canary",
        repo: "acme-obs-stack",
        purpose: "operate",
        desc: "monitor do canary (guardrails do corte)",
        "delivery-after": ["porta-fluxo", "adapta-api"],
        review: "externo: time-sre",
        intent: "intent-checkout-stack",
      },
    },
    {
      id: "intent-consent-center",
      type: "intent",
      label: "central de consentimento e base legal por dado",
      data: {
        id: "intent-consent-center",
        title: "central de consentimento e base legal por dado",
        team: "time-identity",
        "authorized-by": "obj-trust",
        "primary-target": "tgt-identity-consent",
        thesis: "tese-privacidade",
        approach: "direct",
        signal: "touches-contract",
        "contracts-changed": ["acme-user-context"],
        works: [
          {
            id: "central-consentimento",
            repo: "acme-identity",
            purpose: "create",
            desc: "central de consentimento (ver/dar/revogar) + registro de base legal",
            review: "interno",
          },
          {
            id: "contexto-consentimento",
            repo: "acme-web-host",
            purpose: "sustain",
            desc: "acme-user-context ganha campos de consentimento — COORDENAR com a onda do checkout (mesmo contrato, mesma janela)",
            "blocked-by": ["central-consentimento"],
            review: "externo: area-platform",
          },
          {
            id: "propagar-base-legal",
            repo: "acme-data-pipeline",
            purpose: "sustain",
            desc: "warehouse propaga a base legal por dado (consent-coverage nasce daqui)",
            "delivery-after": ["central-consentimento"],
            review: "externo: time-data",
          },
        ],
        next: [
          {
            when: "central no ar",
            then: "campos entram no contrato — revisão COORDENADA com a v4 do checkout",
            gate: "release-rollout",
          },
          {
            when: "cobertura de base legal em 100%",
            then: "outcome sobe no placar de confiança",
          },
          {
            when: "conflito de janela com o checkout",
            then: "decision explícita: uma revisão v4 única OU janelas encadeadas",
          },
        ],
      },
    },
    {
      id: "intent-consent-center::central-consentimento",
      type: "work",
      label: "central-consentimento",
      data: {
        id: "central-consentimento",
        repo: "acme-identity",
        purpose: "create",
        desc: "central de consentimento (ver/dar/revogar) + registro de base legal",
        review: "interno",
        intent: "intent-consent-center",
      },
    },
    {
      id: "intent-consent-center::contexto-consentimento",
      type: "work",
      label: "contexto-consentimento",
      data: {
        id: "contexto-consentimento",
        repo: "acme-web-host",
        purpose: "sustain",
        desc: "acme-user-context ganha campos de consentimento — COORDENAR com a onda do checkout (mesmo contrato, mesma janela)",
        "blocked-by": ["central-consentimento"],
        review: "externo: area-platform",
        intent: "intent-consent-center",
      },
    },
    {
      id: "intent-consent-center::propagar-base-legal",
      type: "work",
      label: "propagar-base-legal",
      data: {
        id: "propagar-base-legal",
        repo: "acme-data-pipeline",
        purpose: "sustain",
        desc: "warehouse propaga a base legal por dado (consent-coverage nasce daqui)",
        "delivery-after": ["central-consentimento"],
        review: "externo: time-data",
        intent: "intent-consent-center",
      },
    },
    {
      id: "intent-cta-upgrade",
      type: "intent",
      label: "CTA contextual de upgrade no billing",
      data: {
        id: "intent-cta-upgrade",
        title: "CTA contextual de upgrade no billing",
        team: "time-billing",
        "authorized-by": "obj-revenue",
        "primary-target": "tgt-billing-conv",
        thesis: "tese-cross-sell",
        approach: "validate-first",
        hypothesis: "um CTA contextual no billing aumenta a conversão de cross-sell em X%",
        "decision-rule": "roda 4 semanas OU 50k exposições; ganha se conversão ↑ X% sem churn ↑",
        signal: "none",
        "contracts-consumed": ["acme-events-schema"],
        works: [
          {
            id: "spike-elegibilidade",
            repo: "acme-api-billing",
            purpose: "discover",
            desc: "EXPLORATION — dá p/ reusar o motor de elegibilidade que já existe? pergunta falsificável + fate",
            timebox: "3d",
            review: "interno",
          },
          {
            id: "api-elegibilidade",
            repo: "acme-api-billing",
            purpose: "create",
            desc: "elegibilidade + endpoint (o fate do spike decide: reusar × construir)",
            "blocked-by": ["spike-elegibilidade"],
            review: "interno",
          },
          {
            id: "ui-cta",
            repo: "acme-mfe-billing",
            purpose: "create",
            desc: "UI do CTA atrás da flag — constrói em paralelo com mock; a integração espera o endpoint",
            "delivery-after": ["api-elegibilidade"],
            review: "interno",
          },
          {
            id: "contas-legadas",
            repo: "acme-core-api",
            module: "mod-accounts",
            purpose: "sustain",
            desc: "expõe leitura de contas legadas p/ a elegibilidade — MONOLITO: o dono é o do MÓDULO",
            review: "externo: time-identity",
          },
          {
            id: "baseline-eventos",
            repo: "acme-analytics",
            purpose: "operate",
            desc: "instrumenta com o schema EXISTENTE (consome sem revisão); pronto ANTES de ligar a flag",
            review: "externo: time-data",
          },
        ],
        next: [
          {
            when: "veredito: ganhou",
            then: "graduation — efetiva a variante; outcome soma no placar",
            gate: "accept-verdict",
          },
          {
            when: "veredito: perdeu",
            then: "cleanup — remove flag/variante; aprendizado registrado",
            gate: "accept-verdict",
          },
          {
            when: "veredito: inconclusivo",
            then: "novo experimento refinado OU vira descoberta",
            gate: "accept-verdict",
          },
        ],
      },
    },
    {
      id: "intent-cta-upgrade::spike-elegibilidade",
      type: "work",
      label: "spike-elegibilidade",
      data: {
        id: "spike-elegibilidade",
        repo: "acme-api-billing",
        purpose: "discover",
        desc: "EXPLORATION — dá p/ reusar o motor de elegibilidade que já existe? pergunta falsificável + fate",
        timebox: "3d",
        review: "interno",
        intent: "intent-cta-upgrade",
      },
    },
    {
      id: "intent-cta-upgrade::api-elegibilidade",
      type: "work",
      label: "api-elegibilidade",
      data: {
        id: "api-elegibilidade",
        repo: "acme-api-billing",
        purpose: "create",
        desc: "elegibilidade + endpoint (o fate do spike decide: reusar × construir)",
        "blocked-by": ["spike-elegibilidade"],
        review: "interno",
        intent: "intent-cta-upgrade",
      },
    },
    {
      id: "intent-cta-upgrade::ui-cta",
      type: "work",
      label: "ui-cta",
      data: {
        id: "ui-cta",
        repo: "acme-mfe-billing",
        purpose: "create",
        desc: "UI do CTA atrás da flag — constrói em paralelo com mock; a integração espera o endpoint",
        "delivery-after": ["api-elegibilidade"],
        review: "interno",
        intent: "intent-cta-upgrade",
      },
    },
    {
      id: "intent-cta-upgrade::contas-legadas",
      type: "work",
      label: "contas-legadas",
      data: {
        id: "contas-legadas",
        repo: "acme-core-api",
        module: "mod-accounts",
        purpose: "sustain",
        desc: "expõe leitura de contas legadas p/ a elegibilidade — MONOLITO: o dono é o do MÓDULO",
        review: "externo: time-identity",
        intent: "intent-cta-upgrade",
      },
    },
    {
      id: "intent-cta-upgrade::baseline-eventos",
      type: "work",
      label: "baseline-eventos",
      data: {
        id: "baseline-eventos",
        repo: "acme-analytics",
        purpose: "operate",
        desc: "instrumenta com o schema EXISTENTE (consome sem revisão); pronto ANTES de ligar a flag",
        review: "externo: time-data",
        intent: "intent-cta-upgrade",
      },
    },
    {
      id: "intent-help-selfservice",
      type: "intent",
      label: "autoatendimento: central de ajuda que resolve sem ticket",
      data: {
        id: "intent-help-selfservice",
        title: "autoatendimento: central de ajuda que resolve sem ticket",
        team: "time-support",
        "authorized-by": "obj-efficiency",
        "primary-target": "tgt-support-cost",
        thesis: "tese-self-service",
        approach: "direct",
        signal: "none",
        "contracts-consumed": ["acme-events-schema"],
        works: [
          {
            id: "base-conhecimento",
            repo: "acme-help-center",
            purpose: "create",
            desc: "base de conhecimento estruturada + busca",
            review: "interno",
          },
          {
            id: "chatbot-deflexao",
            repo: "acme-help-center",
            purpose: "create",
            desc: "chatbot de deflexão (responde antes de abrir ticket)",
            "delivery-after": ["base-conhecimento"],
            review: "interno",
          },
          {
            id: "eventos-deflexao",
            repo: "acme-analytics",
            purpose: "operate",
            desc: "mede deflexão × custo por ticket (consome o schema existente)",
            review: "externo: time-data",
          },
        ],
        next: [
          {
            when: "base no ar",
            then: "chatbot entra por cima; deflexão medida por coorte",
          },
          {
            when: "custo por ticket caiu R%",
            then: "outcome sobe no placar de eficiência",
          },
          {
            when: "satisfação caiu junto",
            then: "escala: vira experimento (validate-first) de formato",
          },
        ],
      },
    },
    {
      id: "intent-help-selfservice::base-conhecimento",
      type: "work",
      label: "base-conhecimento",
      data: {
        id: "base-conhecimento",
        repo: "acme-help-center",
        purpose: "create",
        desc: "base de conhecimento estruturada + busca",
        review: "interno",
        intent: "intent-help-selfservice",
      },
    },
    {
      id: "intent-help-selfservice::chatbot-deflexao",
      type: "work",
      label: "chatbot-deflexao",
      data: {
        id: "chatbot-deflexao",
        repo: "acme-help-center",
        purpose: "create",
        desc: "chatbot de deflexão (responde antes de abrir ticket)",
        "delivery-after": ["base-conhecimento"],
        review: "interno",
        intent: "intent-help-selfservice",
      },
    },
    {
      id: "intent-help-selfservice::eventos-deflexao",
      type: "work",
      label: "eventos-deflexao",
      data: {
        id: "eventos-deflexao",
        repo: "acme-analytics",
        purpose: "operate",
        desc: "mede deflexão × custo por ticket (consome o schema existente)",
        review: "externo: time-data",
        intent: "intent-help-selfservice",
      },
    },
    {
      id: "intent-onboarding-checklist",
      type: "intent",
      label: "checklist guiado de ativação na primeira semana",
      data: {
        id: "intent-onboarding-checklist",
        title: "checklist guiado de ativação na primeira semana",
        team: "time-onboarding",
        "authorized-by": "obj-retention",
        "primary-target": "tgt-onboarding-churn",
        thesis: "tese-onboarding-retencao",
        approach: "validate-first",
        hypothesis:
          "um checklist guiado na 1ª semana aumenta a ativação e derruba o churn em P p.p.",
        "decision-rule": "roda 6 semanas; ganha se churn dos expostos cair P p.p. sem queda de NPS",
        signal: "none",
        "contracts-consumed": ["acme-events-schema"],
        works: [
          {
            id: "flag-checklist",
            repo: "acme-mfe-onboarding",
            purpose: "create",
            desc: "checklist guiado atrás da flag (coorte da 1ª semana)",
            review: "interno",
          },
          {
            id: "baseline-ativacao",
            repo: "acme-analytics",
            purpose: "operate",
            desc: "coortes de ativação × churn (consome o schema existente); pronto antes da flag",
            review: "externo: time-data",
          },
        ],
        next: [
          {
            when: "veredito: ganhou",
            then: "graduation — checklist vira padrão do onboarding",
            gate: "accept-verdict",
          },
          {
            when: "veredito: perdeu",
            then: "cleanup — remove flag; aprendizado registrado",
            gate: "accept-verdict",
          },
          {
            when: "veredito: inconclusivo",
            then: "refina coorte OU vira descoberta",
            gate: "accept-verdict",
          },
        ],
      },
    },
    {
      id: "intent-onboarding-checklist::flag-checklist",
      type: "work",
      label: "flag-checklist",
      data: {
        id: "flag-checklist",
        repo: "acme-mfe-onboarding",
        purpose: "create",
        desc: "checklist guiado atrás da flag (coorte da 1ª semana)",
        review: "interno",
        intent: "intent-onboarding-checklist",
      },
    },
    {
      id: "intent-onboarding-checklist::baseline-ativacao",
      type: "work",
      label: "baseline-ativacao",
      data: {
        id: "baseline-ativacao",
        repo: "acme-analytics",
        purpose: "operate",
        desc: "coortes de ativação × churn (consome o schema existente); pronto antes da flag",
        review: "externo: time-data",
        intent: "intent-onboarding-checklist",
      },
    },
    {
      id: "intent-p99-hardening",
      type: "intent",
      label: "derrubar o p99 da plataforma (timeouts, retries, cache)",
      data: {
        id: "intent-p99-hardening",
        title: "derrubar o p99 da plataforma (timeouts, retries, cache)",
        team: "time-sre",
        "authorized-by": "obj-efficiency",
        "primary-target": "tgt-sre-p99",
        approach: "direct",
        signal: "operational-target",
        works: [
          {
            id: "guardrails-p99",
            repo: "acme-obs-stack",
            purpose: "operate",
            desc: "guardrails de p99 + alertas — MEDIR ANTES de mexer (baseline); a fonte que ATESTA os outcomes",
            review: "interno",
          },
          {
            id: "timeouts-api",
            repo: "acme-checkout-api",
            purpose: "sustain",
            desc: "timeouts + retries (preventivo) — codifica em paralelo; NÃO LIGA antes do baseline",
            "delivery-after": ["guardrails-p99"],
            review: "externo: time-checkout",
          },
          {
            id: "cache-contexto",
            repo: "acme-web-host",
            purpose: "sustain",
            desc: "cache do contexto de usuário (sem mudar o contrato — só a implementação)",
            "delivery-after": ["guardrails-p99"],
            review: "externo: area-platform",
          },
        ],
        next: [
          {
            when: "peças concluídas",
            then: "outcomes sobem no placar OPERACIONAL — attester independente (obs-stack)",
          },
          {
            when: "p99 cedeu",
            then: "guardrails viram monitoramento permanente; a intent fecha",
          },
          {
            when: "p99 NÃO cedeu",
            then: "escala: vira descoberta (investigar causa) OU experimento de performance (validate-first)",
          },
        ],
      },
    },
    {
      id: "intent-p99-hardening::guardrails-p99",
      type: "work",
      label: "guardrails-p99",
      data: {
        id: "guardrails-p99",
        repo: "acme-obs-stack",
        purpose: "operate",
        desc: "guardrails de p99 + alertas — MEDIR ANTES de mexer (baseline); a fonte que ATESTA os outcomes",
        review: "interno",
        intent: "intent-p99-hardening",
      },
    },
    {
      id: "intent-p99-hardening::timeouts-api",
      type: "work",
      label: "timeouts-api",
      data: {
        id: "timeouts-api",
        repo: "acme-checkout-api",
        purpose: "sustain",
        desc: "timeouts + retries (preventivo) — codifica em paralelo; NÃO LIGA antes do baseline",
        "delivery-after": ["guardrails-p99"],
        review: "externo: time-checkout",
        intent: "intent-p99-hardening",
      },
    },
    {
      id: "intent-p99-hardening::cache-contexto",
      type: "work",
      label: "cache-contexto",
      data: {
        id: "cache-contexto",
        repo: "acme-web-host",
        purpose: "sustain",
        desc: "cache do contexto de usuário (sem mudar o contrato — só a implementação)",
        "delivery-after": ["guardrails-p99"],
        review: "externo: area-platform",
        intent: "intent-p99-hardening",
      },
    },
    {
      id: "bug-frete",
      type: "standalone",
      label: "fix: bug-frete",
      data: {
        id: "bug-frete",
        kind: "fix",
        repo: "acme-checkout",
        origin: "suporte reporta: cupom duplo zera o frete",
        "routed-by": "matcher (caps: cupom · frete) — humano confirmou (followed)",
        review: "interno",
        placar: "operational-bucket",
      },
    },
    {
      id: "incidente-checkout",
      type: "standalone",
      label: "incident-response: incidente-checkout",
      data: {
        id: "incidente-checkout",
        kind: "incident-response",
        repo: "acme-checkout-api",
        origin: "alerta do acme-obs-stack às 22:14 — checkout fora do ar (sev alta)",
        severity: "alta",
        mttr: "43min",
        postmortem: "blameless",
        "follow-ups": [
          "fix (peça sustain no acme-checkout-api)",
          "proposta de hardening → intake (com authorized-by ou standalone)",
        ],
        placar: "operational-bucket + MTTR",
      },
    },
    {
      id: "dep-bump-host",
      type: "standalone",
      label: "dep-bump: dep-bump-host",
      data: {
        id: "dep-bump-host",
        kind: "dep-bump",
        repo: "acme-web-host",
        origin: "rotina: lib X 3.x → 4.x",
        review: "externo: area-platform",
        placar: "operational-bucket",
      },
    },
  ],
  edges: [
    {
      id: "cascades-to:obj-revenue->area-growth",
      source: "obj-revenue",
      target: "area-growth",
      type: "cascades-to",
    },
    {
      id: "cascades-to:obj-retention->area-growth",
      source: "obj-retention",
      target: "area-growth",
      type: "cascades-to",
    },
    {
      id: "cascades-to:obj-efficiency->area-platform",
      source: "obj-efficiency",
      target: "area-platform",
      type: "cascades-to",
    },
    {
      id: "cascades-to:obj-trust->area-platform",
      source: "obj-trust",
      target: "area-platform",
      type: "cascades-to",
    },
    {
      id: "cascades-to:obj-retention->area-cx",
      source: "obj-retention",
      target: "area-cx",
      type: "cascades-to",
    },
    {
      id: "cascades-to:obj-efficiency->area-cx",
      source: "obj-efficiency",
      target: "area-cx",
      type: "cascades-to",
    },
    {
      id: "framed-by:obj-revenue->tese-cross-sell",
      source: "obj-revenue",
      target: "tese-cross-sell",
      type: "framed-by",
    },
    {
      id: "framed-by:obj-revenue->tese-pricing-anual",
      source: "obj-revenue",
      target: "tese-pricing-anual",
      type: "framed-by",
    },
    {
      id: "framed-by:obj-retention->tese-onboarding-retencao",
      source: "obj-retention",
      target: "tese-onboarding-retencao",
      type: "framed-by",
    },
    {
      id: "framed-by:obj-retention->tese-suporte-retencao",
      source: "obj-retention",
      target: "tese-suporte-retencao",
      type: "framed-by",
    },
    {
      id: "framed-by:obj-efficiency->tese-eficiencia",
      source: "obj-efficiency",
      target: "tese-eficiencia",
      type: "framed-by",
    },
    {
      id: "framed-by:obj-efficiency->tese-self-service",
      source: "obj-efficiency",
      target: "tese-self-service",
      type: "framed-by",
    },
    {
      id: "framed-by:obj-trust->tese-privacidade",
      source: "obj-trust",
      target: "tese-privacidade",
      type: "framed-by",
    },
    {
      id: "has-team:area-growth->time-billing",
      source: "area-growth",
      target: "time-billing",
      type: "has-team",
    },
    {
      id: "has-team:area-growth->time-onboarding",
      source: "area-growth",
      target: "time-onboarding",
      type: "has-team",
    },
    {
      id: "has-team:area-platform->time-checkout",
      source: "area-platform",
      target: "time-checkout",
      type: "has-team",
    },
    {
      id: "has-team:area-platform->time-data",
      source: "area-platform",
      target: "time-data",
      type: "has-team",
    },
    {
      id: "has-team:area-platform->time-sre",
      source: "area-platform",
      target: "time-sre",
      type: "has-team",
    },
    {
      id: "has-team:area-platform->time-identity",
      source: "area-platform",
      target: "time-identity",
      type: "has-team",
    },
    {
      id: "has-team:area-cx->time-support",
      source: "area-cx",
      target: "time-support",
      type: "has-team",
    },
    {
      id: "owns:time-billing->acme-mfe-billing",
      source: "time-billing",
      target: "acme-mfe-billing",
      type: "owns",
    },
    {
      id: "owns:time-billing->acme-api-billing",
      source: "time-billing",
      target: "acme-api-billing",
      type: "owns",
    },
    {
      id: "owns:time-onboarding->acme-mfe-onboarding",
      source: "time-onboarding",
      target: "acme-mfe-onboarding",
      type: "owns",
    },
    {
      id: "owns:time-checkout->acme-checkout",
      source: "time-checkout",
      target: "acme-checkout",
      type: "owns",
    },
    {
      id: "owns:time-checkout->acme-checkout-api",
      source: "time-checkout",
      target: "acme-checkout-api",
      type: "owns",
    },
    {
      id: "owns:time-data->acme-analytics",
      source: "time-data",
      target: "acme-analytics",
      type: "owns",
    },
    {
      id: "owns:time-data->acme-data-pipeline",
      source: "time-data",
      target: "acme-data-pipeline",
      type: "owns",
    },
    {
      id: "owns:time-sre->acme-obs-stack",
      source: "time-sre",
      target: "acme-obs-stack",
      type: "owns",
    },
    {
      id: "owns:time-identity->acme-identity",
      source: "time-identity",
      target: "acme-identity",
      type: "owns",
    },
    {
      id: "owns:time-support->acme-help-center",
      source: "time-support",
      target: "acme-help-center",
      type: "owns",
    },
    {
      id: "owns:area-platform->acme-web-host",
      source: "area-platform",
      target: "acme-web-host",
      type: "owns",
    },
    {
      id: "owns:area-platform->acme-design-system",
      source: "area-platform",
      target: "acme-design-system",
      type: "owns",
    },
    {
      id: "owns:area-platform->acme-core-api",
      source: "area-platform",
      target: "acme-core-api",
      type: "owns",
    },
    {
      id: "has-module:acme-core-api->acme-core-api#mod-billing",
      source: "acme-core-api",
      target: "acme-core-api#mod-billing",
      type: "has-module",
    },
    {
      id: "owns:time-billing->acme-core-api#mod-billing",
      source: "time-billing",
      target: "acme-core-api#mod-billing",
      type: "owns",
    },
    {
      id: "has-module:acme-core-api->acme-core-api#mod-orders",
      source: "acme-core-api",
      target: "acme-core-api#mod-orders",
      type: "has-module",
    },
    {
      id: "owns:time-checkout->acme-core-api#mod-orders",
      source: "time-checkout",
      target: "acme-core-api#mod-orders",
      type: "owns",
    },
    {
      id: "has-module:acme-core-api->acme-core-api#mod-accounts",
      source: "acme-core-api",
      target: "acme-core-api#mod-accounts",
      type: "has-module",
    },
    {
      id: "owns:time-identity->acme-core-api#mod-accounts",
      source: "time-identity",
      target: "acme-core-api#mod-accounts",
      type: "owns",
    },
    {
      id: "has-module:acme-core-api->acme-core-api#mod-reports",
      source: "acme-core-api",
      target: "acme-core-api#mod-reports",
      type: "has-module",
    },
    {
      id: "owns:time-data->acme-core-api#mod-reports",
      source: "time-data",
      target: "acme-core-api#mod-reports",
      type: "owns",
    },
    {
      id: "publishes:acme-web-host->acme-user-context",
      source: "acme-web-host",
      target: "acme-user-context",
      type: "publishes",
    },
    {
      id: "consumed-by:acme-user-context->acme-mfe-billing",
      source: "acme-user-context",
      target: "acme-mfe-billing",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-user-context->acme-mfe-onboarding",
      source: "acme-user-context",
      target: "acme-mfe-onboarding",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-user-context->acme-checkout",
      source: "acme-user-context",
      target: "acme-checkout",
      type: "consumed-by",
    },
    {
      id: "publishes:acme-design-system->acme-design-tokens",
      source: "acme-design-system",
      target: "acme-design-tokens",
      type: "publishes",
    },
    {
      id: "consumed-by:acme-design-tokens->acme-mfe-billing",
      source: "acme-design-tokens",
      target: "acme-mfe-billing",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-design-tokens->acme-mfe-onboarding",
      source: "acme-design-tokens",
      target: "acme-mfe-onboarding",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-design-tokens->acme-checkout",
      source: "acme-design-tokens",
      target: "acme-checkout",
      type: "consumed-by",
    },
    {
      id: "publishes:acme-analytics->acme-events-schema",
      source: "acme-analytics",
      target: "acme-events-schema",
      type: "publishes",
    },
    {
      id: "consumed-by:acme-events-schema->acme-mfe-billing",
      source: "acme-events-schema",
      target: "acme-mfe-billing",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-events-schema->acme-mfe-onboarding",
      source: "acme-events-schema",
      target: "acme-mfe-onboarding",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-events-schema->acme-checkout",
      source: "acme-events-schema",
      target: "acme-checkout",
      type: "consumed-by",
    },
    {
      id: "consumed-by:acme-events-schema->acme-checkout-api",
      source: "acme-events-schema",
      target: "acme-checkout-api",
      type: "consumed-by",
    },
    {
      id: "has-target:time-billing->tgt-billing-conv",
      source: "time-billing",
      target: "tgt-billing-conv",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-billing-conv->conversion-rate",
      source: "tgt-billing-conv",
      target: "conversion-rate",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-billing-conv->obj-revenue",
      source: "tgt-billing-conv",
      target: "obj-revenue",
      type: "contributes-to",
    },
    {
      id: "has-target:time-onboarding->tgt-onboarding-act",
      source: "time-onboarding",
      target: "tgt-onboarding-act",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-onboarding-act->activation-rate",
      source: "tgt-onboarding-act",
      target: "activation-rate",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-onboarding-act->obj-revenue",
      source: "tgt-onboarding-act",
      target: "obj-revenue",
      type: "contributes-to",
    },
    {
      id: "has-target:time-checkout->tgt-checkout-stack",
      source: "time-checkout",
      target: "tgt-checkout-stack",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-checkout-stack->cost-to-serve",
      source: "tgt-checkout-stack",
      target: "cost-to-serve",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-checkout-stack->obj-efficiency",
      source: "tgt-checkout-stack",
      target: "obj-efficiency",
      type: "contributes-to",
    },
    {
      id: "has-target:time-data->tgt-data-cost",
      source: "time-data",
      target: "tgt-data-cost",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-data-cost->cost-to-serve",
      source: "tgt-data-cost",
      target: "cost-to-serve",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-data-cost->obj-efficiency",
      source: "tgt-data-cost",
      target: "obj-efficiency",
      type: "contributes-to",
    },
    {
      id: "has-target:time-sre->tgt-sre-p99",
      source: "time-sre",
      target: "tgt-sre-p99",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-sre-p99->p99-latency",
      source: "tgt-sre-p99",
      target: "p99-latency",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-sre-p99->obj-efficiency",
      source: "tgt-sre-p99",
      target: "obj-efficiency",
      type: "contributes-to",
    },
    {
      id: "has-target:time-sre->tgt-sre-incidents",
      source: "time-sre",
      target: "tgt-sre-incidents",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-sre-incidents->incident-count",
      source: "tgt-sre-incidents",
      target: "incident-count",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-sre-incidents->obj-efficiency",
      source: "tgt-sre-incidents",
      target: "obj-efficiency",
      type: "contributes-to",
    },
    {
      id: "has-target:time-checkout->tgt-checkout-conv",
      source: "time-checkout",
      target: "tgt-checkout-conv",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-checkout-conv->conversion-rate",
      source: "tgt-checkout-conv",
      target: "conversion-rate",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-checkout-conv->obj-revenue",
      source: "tgt-checkout-conv",
      target: "obj-revenue",
      type: "contributes-to",
    },
    {
      id: "has-target:time-onboarding->tgt-onboarding-churn",
      source: "time-onboarding",
      target: "tgt-onboarding-churn",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-onboarding-churn->churn-rate",
      source: "tgt-onboarding-churn",
      target: "churn-rate",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-onboarding-churn->obj-retention",
      source: "tgt-onboarding-churn",
      target: "obj-retention",
      type: "contributes-to",
    },
    {
      id: "has-target:time-support->tgt-support-churn",
      source: "time-support",
      target: "tgt-support-churn",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-support-churn->churn-rate",
      source: "tgt-support-churn",
      target: "churn-rate",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-support-churn->obj-retention",
      source: "tgt-support-churn",
      target: "obj-retention",
      type: "contributes-to",
    },
    {
      id: "has-target:time-support->tgt-support-cost",
      source: "time-support",
      target: "tgt-support-cost",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-support-cost->ticket-cost",
      source: "tgt-support-cost",
      target: "ticket-cost",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-support-cost->obj-efficiency",
      source: "tgt-support-cost",
      target: "obj-efficiency",
      type: "contributes-to",
    },
    {
      id: "has-target:time-identity->tgt-identity-consent",
      source: "time-identity",
      target: "tgt-identity-consent",
      type: "has-target",
    },
    {
      id: "uses-metric:tgt-identity-consent->consent-coverage",
      source: "tgt-identity-consent",
      target: "consent-coverage",
      type: "uses-metric",
    },
    {
      id: "contributes-to:tgt-identity-consent->obj-trust",
      source: "tgt-identity-consent",
      target: "obj-trust",
      type: "contributes-to",
    },
    {
      id: "authorizes:obj-revenue->intent-checkout-1click",
      source: "obj-revenue",
      target: "intent-checkout-1click",
      type: "authorizes",
    },
    {
      id: "runs:time-checkout->intent-checkout-1click",
      source: "time-checkout",
      target: "intent-checkout-1click",
      type: "runs",
    },
    {
      id: "primary-target:intent-checkout-1click->tgt-checkout-conv",
      source: "intent-checkout-1click",
      target: "tgt-checkout-conv",
      type: "primary-target",
    },
    {
      id: "informs:tese-cross-sell->intent-checkout-1click",
      source: "tese-cross-sell",
      target: "intent-checkout-1click",
      type: "informs",
    },
    {
      id: "consumes:intent-checkout-1click->acme-events-schema",
      source: "intent-checkout-1click",
      target: "acme-events-schema",
      type: "consumes",
    },
    {
      id: "piece:intent-checkout-1click->intent-checkout-1click::flag-1click",
      source: "intent-checkout-1click",
      target: "intent-checkout-1click::flag-1click",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-1click::flag-1click->acme-checkout",
      source: "intent-checkout-1click::flag-1click",
      target: "acme-checkout",
      type: "in-repo",
    },
    {
      id: "piece:intent-checkout-1click->intent-checkout-1click::api-token-pagamento",
      source: "intent-checkout-1click",
      target: "intent-checkout-1click::api-token-pagamento",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-1click::api-token-pagamento->acme-checkout-api",
      source: "intent-checkout-1click::api-token-pagamento",
      target: "acme-checkout-api",
      type: "in-repo",
    },
    {
      id: "piece:intent-checkout-1click->intent-checkout-1click::baseline-1click",
      source: "intent-checkout-1click",
      target: "intent-checkout-1click::baseline-1click",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-1click::baseline-1click->acme-analytics",
      source: "intent-checkout-1click::baseline-1click",
      target: "acme-analytics",
      type: "in-repo",
    },
    {
      id: "authorizes:obj-efficiency->intent-checkout-stack",
      source: "obj-efficiency",
      target: "intent-checkout-stack",
      type: "authorizes",
    },
    {
      id: "runs:time-checkout->intent-checkout-stack",
      source: "time-checkout",
      target: "intent-checkout-stack",
      type: "runs",
    },
    {
      id: "primary-target:intent-checkout-stack->tgt-checkout-stack",
      source: "intent-checkout-stack",
      target: "tgt-checkout-stack",
      type: "primary-target",
    },
    {
      id: "informs:tese-eficiencia->intent-checkout-stack",
      source: "tese-eficiencia",
      target: "intent-checkout-stack",
      type: "informs",
    },
    {
      id: "changes:intent-checkout-stack->acme-user-context",
      source: "intent-checkout-stack",
      target: "acme-user-context",
      type: "changes",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::spike-carrinho",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::spike-carrinho",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::spike-carrinho->acme-checkout",
      source: "intent-checkout-stack::spike-carrinho",
      target: "acme-checkout",
      type: "in-repo",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::componentes-ds",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::componentes-ds",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::componentes-ds->acme-design-system",
      source: "intent-checkout-stack::componentes-ds",
      target: "acme-design-system",
      type: "in-repo",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::porta-fluxo",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::porta-fluxo",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::porta-fluxo->acme-checkout",
      source: "intent-checkout-stack::porta-fluxo",
      target: "acme-checkout",
      type: "in-repo",
    },
    {
      id: "blocked-by:intent-checkout-stack::porta-fluxo->intent-checkout-stack::spike-carrinho",
      source: "intent-checkout-stack::porta-fluxo",
      target: "intent-checkout-stack::spike-carrinho",
      type: "blocked-by",
    },
    {
      id: "delivery-after:intent-checkout-stack::porta-fluxo->intent-checkout-stack::componentes-ds",
      source: "intent-checkout-stack::porta-fluxo",
      target: "intent-checkout-stack::componentes-ds",
      type: "delivery-after",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::adapta-api",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::adapta-api",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::adapta-api->acme-checkout-api",
      source: "intent-checkout-stack::adapta-api",
      target: "acme-checkout-api",
      type: "in-repo",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::estrangula-pedidos",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::estrangula-pedidos",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::estrangula-pedidos->acme-core-api",
      source: "intent-checkout-stack::estrangula-pedidos",
      target: "acme-core-api",
      type: "in-repo",
    },
    {
      id: "in-module:intent-checkout-stack::estrangula-pedidos->acme-core-api#mod-orders",
      source: "intent-checkout-stack::estrangula-pedidos",
      target: "acme-core-api#mod-orders",
      type: "in-module",
    },
    {
      id: "blocked-by:intent-checkout-stack::estrangula-pedidos->intent-checkout-stack::spike-carrinho",
      source: "intent-checkout-stack::estrangula-pedidos",
      target: "intent-checkout-stack::spike-carrinho",
      type: "blocked-by",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::revisao-contrato",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::revisao-contrato",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::revisao-contrato->acme-web-host",
      source: "intent-checkout-stack::revisao-contrato",
      target: "acme-web-host",
      type: "in-repo",
    },
    {
      id: "piece:intent-checkout-stack->intent-checkout-stack::monitor-canary",
      source: "intent-checkout-stack",
      target: "intent-checkout-stack::monitor-canary",
      type: "piece",
    },
    {
      id: "in-repo:intent-checkout-stack::monitor-canary->acme-obs-stack",
      source: "intent-checkout-stack::monitor-canary",
      target: "acme-obs-stack",
      type: "in-repo",
    },
    {
      id: "delivery-after:intent-checkout-stack::monitor-canary->intent-checkout-stack::porta-fluxo",
      source: "intent-checkout-stack::monitor-canary",
      target: "intent-checkout-stack::porta-fluxo",
      type: "delivery-after",
    },
    {
      id: "delivery-after:intent-checkout-stack::monitor-canary->intent-checkout-stack::adapta-api",
      source: "intent-checkout-stack::monitor-canary",
      target: "intent-checkout-stack::adapta-api",
      type: "delivery-after",
    },
    {
      id: "authorizes:obj-trust->intent-consent-center",
      source: "obj-trust",
      target: "intent-consent-center",
      type: "authorizes",
    },
    {
      id: "runs:time-identity->intent-consent-center",
      source: "time-identity",
      target: "intent-consent-center",
      type: "runs",
    },
    {
      id: "primary-target:intent-consent-center->tgt-identity-consent",
      source: "intent-consent-center",
      target: "tgt-identity-consent",
      type: "primary-target",
    },
    {
      id: "informs:tese-privacidade->intent-consent-center",
      source: "tese-privacidade",
      target: "intent-consent-center",
      type: "informs",
    },
    {
      id: "changes:intent-consent-center->acme-user-context",
      source: "intent-consent-center",
      target: "acme-user-context",
      type: "changes",
    },
    {
      id: "piece:intent-consent-center->intent-consent-center::central-consentimento",
      source: "intent-consent-center",
      target: "intent-consent-center::central-consentimento",
      type: "piece",
    },
    {
      id: "in-repo:intent-consent-center::central-consentimento->acme-identity",
      source: "intent-consent-center::central-consentimento",
      target: "acme-identity",
      type: "in-repo",
    },
    {
      id: "piece:intent-consent-center->intent-consent-center::contexto-consentimento",
      source: "intent-consent-center",
      target: "intent-consent-center::contexto-consentimento",
      type: "piece",
    },
    {
      id: "in-repo:intent-consent-center::contexto-consentimento->acme-web-host",
      source: "intent-consent-center::contexto-consentimento",
      target: "acme-web-host",
      type: "in-repo",
    },
    {
      id: "blocked-by:intent-consent-center::contexto-consentimento->intent-consent-center::central-consentimento",
      source: "intent-consent-center::contexto-consentimento",
      target: "intent-consent-center::central-consentimento",
      type: "blocked-by",
    },
    {
      id: "piece:intent-consent-center->intent-consent-center::propagar-base-legal",
      source: "intent-consent-center",
      target: "intent-consent-center::propagar-base-legal",
      type: "piece",
    },
    {
      id: "in-repo:intent-consent-center::propagar-base-legal->acme-data-pipeline",
      source: "intent-consent-center::propagar-base-legal",
      target: "acme-data-pipeline",
      type: "in-repo",
    },
    {
      id: "delivery-after:intent-consent-center::propagar-base-legal->intent-consent-center::central-consentimento",
      source: "intent-consent-center::propagar-base-legal",
      target: "intent-consent-center::central-consentimento",
      type: "delivery-after",
    },
    {
      id: "authorizes:obj-revenue->intent-cta-upgrade",
      source: "obj-revenue",
      target: "intent-cta-upgrade",
      type: "authorizes",
    },
    {
      id: "runs:time-billing->intent-cta-upgrade",
      source: "time-billing",
      target: "intent-cta-upgrade",
      type: "runs",
    },
    {
      id: "primary-target:intent-cta-upgrade->tgt-billing-conv",
      source: "intent-cta-upgrade",
      target: "tgt-billing-conv",
      type: "primary-target",
    },
    {
      id: "informs:tese-cross-sell->intent-cta-upgrade",
      source: "tese-cross-sell",
      target: "intent-cta-upgrade",
      type: "informs",
    },
    {
      id: "consumes:intent-cta-upgrade->acme-events-schema",
      source: "intent-cta-upgrade",
      target: "acme-events-schema",
      type: "consumes",
    },
    {
      id: "piece:intent-cta-upgrade->intent-cta-upgrade::spike-elegibilidade",
      source: "intent-cta-upgrade",
      target: "intent-cta-upgrade::spike-elegibilidade",
      type: "piece",
    },
    {
      id: "in-repo:intent-cta-upgrade::spike-elegibilidade->acme-api-billing",
      source: "intent-cta-upgrade::spike-elegibilidade",
      target: "acme-api-billing",
      type: "in-repo",
    },
    {
      id: "piece:intent-cta-upgrade->intent-cta-upgrade::api-elegibilidade",
      source: "intent-cta-upgrade",
      target: "intent-cta-upgrade::api-elegibilidade",
      type: "piece",
    },
    {
      id: "in-repo:intent-cta-upgrade::api-elegibilidade->acme-api-billing",
      source: "intent-cta-upgrade::api-elegibilidade",
      target: "acme-api-billing",
      type: "in-repo",
    },
    {
      id: "blocked-by:intent-cta-upgrade::api-elegibilidade->intent-cta-upgrade::spike-elegibilidade",
      source: "intent-cta-upgrade::api-elegibilidade",
      target: "intent-cta-upgrade::spike-elegibilidade",
      type: "blocked-by",
    },
    {
      id: "piece:intent-cta-upgrade->intent-cta-upgrade::ui-cta",
      source: "intent-cta-upgrade",
      target: "intent-cta-upgrade::ui-cta",
      type: "piece",
    },
    {
      id: "in-repo:intent-cta-upgrade::ui-cta->acme-mfe-billing",
      source: "intent-cta-upgrade::ui-cta",
      target: "acme-mfe-billing",
      type: "in-repo",
    },
    {
      id: "delivery-after:intent-cta-upgrade::ui-cta->intent-cta-upgrade::api-elegibilidade",
      source: "intent-cta-upgrade::ui-cta",
      target: "intent-cta-upgrade::api-elegibilidade",
      type: "delivery-after",
    },
    {
      id: "piece:intent-cta-upgrade->intent-cta-upgrade::contas-legadas",
      source: "intent-cta-upgrade",
      target: "intent-cta-upgrade::contas-legadas",
      type: "piece",
    },
    {
      id: "in-repo:intent-cta-upgrade::contas-legadas->acme-core-api",
      source: "intent-cta-upgrade::contas-legadas",
      target: "acme-core-api",
      type: "in-repo",
    },
    {
      id: "in-module:intent-cta-upgrade::contas-legadas->acme-core-api#mod-accounts",
      source: "intent-cta-upgrade::contas-legadas",
      target: "acme-core-api#mod-accounts",
      type: "in-module",
    },
    {
      id: "piece:intent-cta-upgrade->intent-cta-upgrade::baseline-eventos",
      source: "intent-cta-upgrade",
      target: "intent-cta-upgrade::baseline-eventos",
      type: "piece",
    },
    {
      id: "in-repo:intent-cta-upgrade::baseline-eventos->acme-analytics",
      source: "intent-cta-upgrade::baseline-eventos",
      target: "acme-analytics",
      type: "in-repo",
    },
    {
      id: "authorizes:obj-efficiency->intent-help-selfservice",
      source: "obj-efficiency",
      target: "intent-help-selfservice",
      type: "authorizes",
    },
    {
      id: "runs:time-support->intent-help-selfservice",
      source: "time-support",
      target: "intent-help-selfservice",
      type: "runs",
    },
    {
      id: "primary-target:intent-help-selfservice->tgt-support-cost",
      source: "intent-help-selfservice",
      target: "tgt-support-cost",
      type: "primary-target",
    },
    {
      id: "informs:tese-self-service->intent-help-selfservice",
      source: "tese-self-service",
      target: "intent-help-selfservice",
      type: "informs",
    },
    {
      id: "consumes:intent-help-selfservice->acme-events-schema",
      source: "intent-help-selfservice",
      target: "acme-events-schema",
      type: "consumes",
    },
    {
      id: "piece:intent-help-selfservice->intent-help-selfservice::base-conhecimento",
      source: "intent-help-selfservice",
      target: "intent-help-selfservice::base-conhecimento",
      type: "piece",
    },
    {
      id: "in-repo:intent-help-selfservice::base-conhecimento->acme-help-center",
      source: "intent-help-selfservice::base-conhecimento",
      target: "acme-help-center",
      type: "in-repo",
    },
    {
      id: "piece:intent-help-selfservice->intent-help-selfservice::chatbot-deflexao",
      source: "intent-help-selfservice",
      target: "intent-help-selfservice::chatbot-deflexao",
      type: "piece",
    },
    {
      id: "in-repo:intent-help-selfservice::chatbot-deflexao->acme-help-center",
      source: "intent-help-selfservice::chatbot-deflexao",
      target: "acme-help-center",
      type: "in-repo",
    },
    {
      id: "delivery-after:intent-help-selfservice::chatbot-deflexao->intent-help-selfservice::base-conhecimento",
      source: "intent-help-selfservice::chatbot-deflexao",
      target: "intent-help-selfservice::base-conhecimento",
      type: "delivery-after",
    },
    {
      id: "piece:intent-help-selfservice->intent-help-selfservice::eventos-deflexao",
      source: "intent-help-selfservice",
      target: "intent-help-selfservice::eventos-deflexao",
      type: "piece",
    },
    {
      id: "in-repo:intent-help-selfservice::eventos-deflexao->acme-analytics",
      source: "intent-help-selfservice::eventos-deflexao",
      target: "acme-analytics",
      type: "in-repo",
    },
    {
      id: "authorizes:obj-retention->intent-onboarding-checklist",
      source: "obj-retention",
      target: "intent-onboarding-checklist",
      type: "authorizes",
    },
    {
      id: "runs:time-onboarding->intent-onboarding-checklist",
      source: "time-onboarding",
      target: "intent-onboarding-checklist",
      type: "runs",
    },
    {
      id: "primary-target:intent-onboarding-checklist->tgt-onboarding-churn",
      source: "intent-onboarding-checklist",
      target: "tgt-onboarding-churn",
      type: "primary-target",
    },
    {
      id: "informs:tese-onboarding-retencao->intent-onboarding-checklist",
      source: "tese-onboarding-retencao",
      target: "intent-onboarding-checklist",
      type: "informs",
    },
    {
      id: "consumes:intent-onboarding-checklist->acme-events-schema",
      source: "intent-onboarding-checklist",
      target: "acme-events-schema",
      type: "consumes",
    },
    {
      id: "piece:intent-onboarding-checklist->intent-onboarding-checklist::flag-checklist",
      source: "intent-onboarding-checklist",
      target: "intent-onboarding-checklist::flag-checklist",
      type: "piece",
    },
    {
      id: "in-repo:intent-onboarding-checklist::flag-checklist->acme-mfe-onboarding",
      source: "intent-onboarding-checklist::flag-checklist",
      target: "acme-mfe-onboarding",
      type: "in-repo",
    },
    {
      id: "piece:intent-onboarding-checklist->intent-onboarding-checklist::baseline-ativacao",
      source: "intent-onboarding-checklist",
      target: "intent-onboarding-checklist::baseline-ativacao",
      type: "piece",
    },
    {
      id: "in-repo:intent-onboarding-checklist::baseline-ativacao->acme-analytics",
      source: "intent-onboarding-checklist::baseline-ativacao",
      target: "acme-analytics",
      type: "in-repo",
    },
    {
      id: "authorizes:obj-efficiency->intent-p99-hardening",
      source: "obj-efficiency",
      target: "intent-p99-hardening",
      type: "authorizes",
    },
    {
      id: "runs:time-sre->intent-p99-hardening",
      source: "time-sre",
      target: "intent-p99-hardening",
      type: "runs",
    },
    {
      id: "primary-target:intent-p99-hardening->tgt-sre-p99",
      source: "intent-p99-hardening",
      target: "tgt-sre-p99",
      type: "primary-target",
    },
    {
      id: "piece:intent-p99-hardening->intent-p99-hardening::guardrails-p99",
      source: "intent-p99-hardening",
      target: "intent-p99-hardening::guardrails-p99",
      type: "piece",
    },
    {
      id: "in-repo:intent-p99-hardening::guardrails-p99->acme-obs-stack",
      source: "intent-p99-hardening::guardrails-p99",
      target: "acme-obs-stack",
      type: "in-repo",
    },
    {
      id: "piece:intent-p99-hardening->intent-p99-hardening::timeouts-api",
      source: "intent-p99-hardening",
      target: "intent-p99-hardening::timeouts-api",
      type: "piece",
    },
    {
      id: "in-repo:intent-p99-hardening::timeouts-api->acme-checkout-api",
      source: "intent-p99-hardening::timeouts-api",
      target: "acme-checkout-api",
      type: "in-repo",
    },
    {
      id: "delivery-after:intent-p99-hardening::timeouts-api->intent-p99-hardening::guardrails-p99",
      source: "intent-p99-hardening::timeouts-api",
      target: "intent-p99-hardening::guardrails-p99",
      type: "delivery-after",
    },
    {
      id: "piece:intent-p99-hardening->intent-p99-hardening::cache-contexto",
      source: "intent-p99-hardening",
      target: "intent-p99-hardening::cache-contexto",
      type: "piece",
    },
    {
      id: "in-repo:intent-p99-hardening::cache-contexto->acme-web-host",
      source: "intent-p99-hardening::cache-contexto",
      target: "acme-web-host",
      type: "in-repo",
    },
    {
      id: "delivery-after:intent-p99-hardening::cache-contexto->intent-p99-hardening::guardrails-p99",
      source: "intent-p99-hardening::cache-contexto",
      target: "intent-p99-hardening::guardrails-p99",
      type: "delivery-after",
    },
    {
      id: "in-repo:bug-frete->acme-checkout",
      source: "bug-frete",
      target: "acme-checkout",
      type: "in-repo",
    },
    {
      id: "in-repo:incidente-checkout->acme-checkout-api",
      source: "incidente-checkout",
      target: "acme-checkout-api",
      type: "in-repo",
    },
    {
      id: "in-repo:dep-bump-host->acme-web-host",
      source: "dep-bump-host",
      target: "acme-web-host",
      type: "in-repo",
    },
  ],
  issues: [],
  profiles: {
    is: "perfis operacionais mínimos por forma de org (G6): cada perfil diz que NÓS existem, que GATES colapsam e que CAMPOS são obrigatórios — colapso LIMPO, não princípio abstrato",
    law: "a org declara UM perfil + desvios EXPLÍCITOS; mudar de perfil = mutação profile-change (dangerous). Perfis derivam por role-collapse parametrizado (G13) — o compact cobre o small-team (PM+TL+eng) sem um 4º arquétipo fixo",
    declaration: {
      fields: ["scope", "profile", "eligibility", "approved-by", "ttl", "review-at"],
      eligibility:
        "compact/solo exigem elegibilidade DECLARÁVEL e verificável (nº de pessoas/papéis no escopo); org com papéis separados NÃO é elegível a solo — o dev solo REAL nunca é bloqueado",
      approver:
        "declaração de compact/solo por um GRUPO exige approver FORA do escopo (SoD aplicado ao próprio perfil); solo individual = self, com badge",
      ttl: "toda declaração tem ttl/review-at; vencida → dashboard marca profile-stale",
      badge:
        "o perfil (e os desvios) aparece como BADGE nos dashboards/rollups do escopo — self-attested/collapsed é VISÍVEL, nunca implícito",
    },
    profiles: {
      full: {
        for: "org com papéis separados (a full-team da simulação)",
        nodes: "business-tier completo + 3 camadas + contract + intake + outcome",
        gates: ["approve-objective", "activate-intent", "release-rollout", "accept-verdict"],
        sod: "completo — requester ≠ approver ≠ owner-attester · target-definer ≠ actual-attester",
        "required-fields":
          "envelope L8 inteiro · outcome com attester independente · aggregation declarada",
        enforcement:
          "F11 (opção C): mutação ruler-authority SEM par = BLOQUEADA (soft-mandatory; break-glass logado + revisão retroativa é a saída); demais dangerous = detecção (dangerous-unreviewed)",
      },
      compact: {
        for: "time pequeno (o trio da simulação; o small-team deriva daqui por role-collapse)",
        nodes:
          "business-objective (1-2 níveis) + intent + execution-unit (colapsa no trivial) + repo-work + outcome",
        gates:
          "activate-intent + accept-verdict; os demais colapsam no MESMO humano, com colapso LOGADO",
        sod: "independência de negócio no gate; autocertificação técnica DECLARADA como gap + mitigação (revisão cruzada / trusted-source externo)",
        "required-fields":
          "outcome ainda exige attester (pode ser a FONTE de dados, não uma pessoa) · aggregation declarada",
        enforcement:
          "F11: tudo detecção (dangerous-unreviewed) + revisão retroativa em CADÊNCIA (não trava)",
      },
      solo: {
        for: "dev solo",
        nodes: "repo-work + outcome self-attested; intent/objective opcionais (colapsam)",
        gates: "nenhum — self-log append-only substitui (break-glass permanente, logado)",
        sod: "dispensado EXPLICITAMENTE com trade-off logado; dashboard marca self-attested",
        "required-fields": "registro append-only (o grafo continua contando a história)",
        enforcement: "F11: detecção/self-log — não se bloqueia o solo",
      },
    },
  },
};
