import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { run } from "./main.js";
import { siteCommandSurface } from "./siteFlowCopy.js";

/**
 * Gerador de cenários de terminal do site (B2 — "terminal não pode mentir").
 *
 * Cada cenário tem uma SUPERFÍCIE:
 *  - public      → consumidor do framework (`npx ai-guidelines …`);
 *  - contributor → quem contribui no próprio repo ai-guidelines (`npm run flow …`).
 *
 * E uma CLASSE de procedência:
 *  - real   → stdout capturado de execução real (dry-run/--help). Determinístico.
 *  - guided → linhas curadas, genéricas e consumer-safe; o NOME do comando é
 *             validado contra o registry (fidelidade), os exemplos não vazam
 *             identificadores internos (PR/spec/sub-checkpoint).
 *
 * O site exibe `kind` como badge e usa `surface` para separar perfis.
 */

const GENERATED_NOTICE = "Generated by npm run site:scenarios:sync. Do not edit manually.";
const OUTPUT_RELATIVE_PATH = "site/src/generated/flow-scenarios.generated.ts";

type Logger = Pick<typeof console, "error" | "log">;

export type ScenarioKind = "real" | "guided";
export type ScenarioSurface = "public" | "contributor";

export interface FlowScenario {
  readonly id: string;
  readonly title: string;
  readonly kind: ScenarioKind;
  readonly surface: ScenarioSurface;
  readonly command: string;
  readonly note: string;
  readonly exitCode: number | null;
  readonly lines: readonly string[];
}

export function siteScenariosOutputPath(repoRoot: string): string {
  return path.join(repoRoot, OUTPUT_RELATIVE_PATH);
}

interface RealSpec {
  readonly id: string;
  readonly title: string;
  readonly surface: ScenarioSurface;
  readonly command: string;
  readonly note: string;
  /** argv passado ao runtime real. `--target` é injetado quando `withTarget`. */
  readonly argv: readonly string[];
  readonly withTarget?: boolean;
  readonly seed?: (targetDir: string) => void;
}

interface GuidedSpec {
  readonly id: string;
  readonly title: string;
  readonly surface: ScenarioSurface;
  /** Invocação exibida (consumer-safe / genérica). */
  readonly command: string;
  /** Nome canônico do comando — validado contra o registry (fidelidade). */
  readonly commandName: string;
  readonly note: string;
  /** Linhas curadas (genéricas). Prefixo já incluso (`$ npx …` / texto). */
  readonly lines: readonly string[];
}

const REAL_SPECS: readonly RealSpec[] = [
  {
    id: "new-project",
    title: "Projeto novo — init em pasta limpa",
    surface: "public",
    command: "npx ai-guidelines init --dry-run",
    note: "Saída real do runtime em modo dry-run (nada é escrito).",
    withTarget: true,
    argv: [
      "init",
      "--dry-run",
      "--name",
      "meu-app",
      "--package-manager",
      "npm",
      "--providers",
      "claude,gemini",
      "--yes",
    ],
  },
  {
    id: "existing-repo",
    title: "Repo existente — adopt conservador",
    surface: "public",
    command: "npx ai-guidelines adopt --dry-run",
    note: "Saída real: adopt preserva conteúdo e aborta conservador ao achar conflito sem --force.",
    withTarget: true,
    argv: ["adopt", "--dry-run", "--providers", "claude", "--yes"],
    seed: (targetDir) => {
      writeFileSync(
        path.join(targetDir, "package.json"),
        `${JSON.stringify(
          { name: "meu-projeto", version: "1.0.0", devDependencies: { standard: "^17.0.0" } },
          null,
          2
        )}\n`
      );
    },
  },
  {
    id: "governed-repo",
    title: "Repo já governado — update do baseline",
    surface: "public",
    command: "npx ai-guidelines update --dry-run",
    note: "Saída real: update reaplica runtime/templates/práticas via managed blocks (dry-run).",
    withTarget: true,
    argv: ["update", "--dry-run", "--yes"],
    seed: (targetDir) => {
      writeFileSync(
        path.join(targetDir, "package.json"),
        `${JSON.stringify({ name: "meu-projeto", version: "2.1.0" }, null, 2)}\n`
      );
    },
  },
  {
    id: "update-providers",
    title: "Trocar assistentes — update --providers",
    surface: "public",
    command: "npx ai-guidelines update --providers claude,openai --dry-run",
    note: "Saída real: atualizar os assistentes de IA é uma seleção, não um comando à parte.",
    withTarget: true,
    argv: ["update", "--providers", "claude,openai", "--dry-run", "--yes"],
    seed: (targetDir) => {
      writeFileSync(
        path.join(targetDir, "package.json"),
        `${JSON.stringify({ name: "meu-projeto", version: "2.1.0" }, null, 2)}\n`
      );
    },
  },
  {
    id: "cli-help",
    title: "Lista de comandos — --help",
    surface: "public",
    command: "npx ai-guidelines --help",
    note: "Saída real do --help: a porta pública começa por `npx ai-guidelines`; o alias local fica separado como uso interno do repo-fonte.",
    withTarget: false,
    argv: ["--help"],
  },
];

const GUIDED_SPECS: readonly GuidedSpec[] = [
  {
    id: "daily-work",
    title: "Uso diário — orientação de trabalho",
    surface: "public",
    command: "npx ai-guidelines work",
    commandName: "work",
    note: "Exemplo guiado (consumer-safe): rode no seu repo para o briefing real do estado.",
    lines: [
      "$ npx ai-guidelines work",
      "Estado atual: spec ativa, PR e working tree",
      "Próxima ação recomendada",
      "Validações e quando parar",
    ],
  },
  {
    id: "multi-spec",
    title: "Múltiplas specs — escolher a frente certa",
    surface: "public",
    command: "npx ai-guidelines specs",
    commandName: "specs",
    note: "Exemplo guiado: `specs` lista as specs abertas do índice público do seu projeto.",
    lines: [
      "$ npx ai-guidelines specs",
      "Specs abertas no índice do projeto",
      "id · branch esperada · PR associado",
      "Divergência aparece como bloqueio, não suposição",
    ],
  },
  {
    id: "peer-review",
    title: "Review entre pares — PR de um colega",
    surface: "public",
    command: "npx ai-guidelines peer-review <pr> --brief-only",
    commandName: "peer-review",
    note: "Exemplo guiado: abre o PR de um colega sem misturar com a sua branch atual.",
    lines: [
      "$ npx ai-guidelines peer-review <pr> --brief-only",
      "Briefing do PR: título, branch, base e working tree",
      "Worktree separado preserva a sua branch",
      "Nada é alterado em modo brief-only",
    ],
  },
  {
    id: "contributor-flow",
    title: "Fluxo interno do repo ai-guidelines",
    surface: "contributor",
    command: "npm run flow",
    commandName: "work",
    note: "Uso interno: neste repositório, `npm run flow` é o alias local do guia situado para quem contribui no próprio ai-guidelines.",
    lines: [
      "$ npm run flow",
      "Guia situado: estado, próxima ação e decisões governadas",
      "$ npm run flow -- decide --brief-only",
      "Decisões reservadas ao humano (Ready, avanço, merge) com bloqueios",
      "$ npm run validate",
      "Gate completo de validação do próprio framework",
    ],
  },
];

function captureRun(): {
  logger: { info(m: string): void; error(m: string): void };
  lines: string[];
} {
  const lines: string[] = [];
  return {
    logger: { info: (m: string) => lines.push(m), error: (m: string) => lines.push(m) },
    lines,
  };
}

function redact(line: string, targetDir: string, tmpDir: string): string {
  return line.split(targetDir).join("<target>").split(tmpDir).join("<tmp>");
}

async function buildRealScenario(spec: RealSpec): Promise<FlowScenario> {
  const base = {
    id: spec.id,
    title: spec.title,
    kind: "real" as const,
    surface: spec.surface,
    command: spec.command,
    note: spec.note,
  };

  if (spec.withTarget === false) {
    const { logger, lines } = captureRun();
    const exitCode = await run([...spec.argv], { logger });
    return { ...base, exitCode, lines: lines.flatMap((line) => line.split("\n")) };
  }

  const tmpDir = mkdtempSync(path.join(os.tmpdir(), "aig-scenario-"));
  const targetDir = path.join(tmpDir, "repo");
  try {
    mkdirSync(targetDir, { recursive: true });
    spec.seed?.(targetDir);
    const { logger, lines } = captureRun();
    const exitCode = await run([...spec.argv, "--target", targetDir], { logger });
    return {
      ...base,
      exitCode,
      lines: lines
        .flatMap((line) => line.split("\n"))
        .map((line) => redact(line, targetDir, tmpDir)),
    };
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

function buildGuidedScenario(spec: GuidedSpec): FlowScenario {
  // Fidelidade: o NOME do comando exibido tem de existir no registry real.
  const exists = siteCommandSurface().some((command) => command.name === spec.commandName);
  if (!exists) {
    throw new Error(`siteScenarios: comando guiado "${spec.commandName}" não existe no registry.`);
  }
  return {
    id: spec.id,
    title: spec.title,
    kind: "guided",
    surface: spec.surface,
    command: spec.command,
    note: spec.note,
    exitCode: null,
    lines: spec.lines,
  };
}

export async function buildSiteScenarios(): Promise<readonly FlowScenario[]> {
  const real: FlowScenario[] = [];
  for (const spec of REAL_SPECS) {
    real.push(await buildRealScenario(spec));
  }
  const guided = GUIDED_SPECS.map(buildGuidedScenario);
  return [...real, ...guided];
}

export async function renderSiteScenariosScript(): Promise<string> {
  const scenarios = await buildSiteScenarios();
  return `// ${GENERATED_NOTICE}\n// prettier-ignore\nexport const AI_GUIDELINES_FLOW_SCENARIOS = ${JSON.stringify(
    scenarios,
    null,
    2
  )} as const;\n`;
}

export async function syncSiteScenarios(repoRoot: string): Promise<void> {
  const outputPath = siteScenariosOutputPath(repoRoot);
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, await renderSiteScenariosScript(), "utf-8");
}

export async function checkSiteScenarios(repoRoot: string): Promise<readonly string[]> {
  const outputPath = siteScenariosOutputPath(repoRoot);
  const expected = await renderSiteScenariosScript();
  if (!existsSync(outputPath)) {
    return [`${OUTPUT_RELATIVE_PATH} não existe; rode npm run site:scenarios:sync`];
  }
  const actual = readFileSync(outputPath, "utf-8");
  if (actual !== expected) {
    return [
      `${OUTPUT_RELATIVE_PATH} diverge dos transcripts do runtime; rode npm run site:scenarios:sync`,
    ];
  }
  return [];
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
  repoRoot = process.cwd(),
  logger: Logger = console
): Promise<number> {
  const command = argv[0] ?? "check";
  if (command === "sync") {
    await syncSiteScenarios(repoRoot);
    logger.log(`✅ site:scenarios:sync — ${OUTPUT_RELATIVE_PATH} gerado do runtime real.`);
    return 0;
  }
  if (command === "check") {
    const violations = await checkSiteScenarios(repoRoot);
    if (violations.length > 0) {
      logger.error(
        "❌ site:scenarios:check encontrou drift entre o site e os transcripts do runtime:\n" +
          violations.map((violation) => `  - ${violation}`).join("\n")
      );
      return 1;
    }
    logger.log("✅ site:scenarios:check — transcripts do site sincronizados com o runtime.");
    return 0;
  }
  logger.error("Uso: node dist/cli/siteScenarios.js [check|sync]");
  return 2;
}

if (require.main === module) {
  void main().then((exitCode) => {
    if (exitCode !== 0) process.exitCode = exitCode;
  });
}
