import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { FLOW_COPY } from "./copy/flowCopy.js";
import { buildRegistry } from "./registry/buildRegistry.js";
import { buildDecisionRegistry } from "./decide/registry.js";
import { INTENT_CATALOG } from "./registry/intentCatalog.js";
import { getSupportedProviders } from "../domain/provisioning/ProviderCatalog.js";
import { FEATURE_OPTIONS } from "../domain/provisioning/FeatureCatalog.js";

const GENERATED_NOTICE = "Generated by npm run site:flow:sync. Do not edit manually.";
const OUTPUT_RELATIVE_PATH = "site/src/generated/flow-copy.generated.ts";

type Logger = Pick<typeof console, "error" | "log">;

export function siteFlowCopyOutputPath(repoRoot: string): string {
  return path.join(repoRoot, OUTPUT_RELATIVE_PATH);
}

/**
 * Superfície de comandos REAL projetada do registry da CLI (SSOT do dispatch).
 * O site consome isto — nunca hard-coda nomes/flags/subcomandos — fechando o
 * achado B1 (segunda fonte de verdade). Determinístico: `commands()` já ordena
 * por nome e remove aliases.
 */
export interface SiteCommandDescriptor {
  readonly name: string;
  readonly aliases: readonly string[];
  readonly description: string;
  readonly usage: readonly string[];
  readonly subcommands: readonly string[];
}

export function siteCommandSurface(): readonly SiteCommandDescriptor[] {
  return buildRegistry()
    .commands()
    .map((command) => ({
      name: command.name,
      aliases: [...(command.aliases ?? [])],
      description: command.description,
      usage: [...(command.usage ?? [])],
      subcommands: [...(command.subcommands ?? [])],
    }));
}

/**
 * Decisões reservadas ao humano REAIS, projetadas do registry de decisões
 * (CO-3). O site descreve Ready/Human Gate/transição a partir desta lista —
 * fecha A2 (o site não promete capacidade de decisão que o runtime não tem).
 */
export interface SiteDecisionDescriptor {
  readonly id: string;
  readonly title: string;
}

export function siteDecisionSurface(): readonly SiteDecisionDescriptor[] {
  return buildDecisionRegistry()
    .definitions()
    .map((definition) => ({ id: definition.id, title: definition.title }));
}

export function siteFlowCopyPayload(): unknown {
  return {
    locale: FLOW_COPY.locale,
    common: FLOW_COPY.common,
    wizard: {
      mainQuestion: FLOW_COPY.wizard.mainQuestion,
      menu: FLOW_COPY.wizard.menu,
      summary: FLOW_COPY.wizard.summary,
      validation: FLOW_COPY.wizard.validation,
    },
    cockpit: {
      title: FLOW_COPY.cockpit.title,
      useful: FLOW_COPY.cockpit.useful,
    },
    providers: FLOW_COPY.providers,
    features: FLOW_COPY.features,
    provisioning: {
      providerQuestion: FLOW_COPY.provisioning.providerQuestion,
      featureInstallQuestion: FLOW_COPY.provisioning.featureInstallQuestion,
      featureUpdateQuestion: FLOW_COPY.provisioning.featureUpdateQuestion,
      providerGroups: FLOW_COPY.provisioning.providerGroups,
      featureGroups: FLOW_COPY.provisioning.featureGroups,
      operationLabels: FLOW_COPY.provisioning.operationLabels,
      operationActionLabels: FLOW_COPY.provisioning.operationActionLabels,
      operationTitles: FLOW_COPY.provisioning.operationTitles,
      mainHints: FLOW_COPY.provisioning.mainHints,
      detected: FLOW_COPY.provisioning.detected,
      flow: {
        intro: FLOW_COPY.provisioning.flow.intro,
        prompts: FLOW_COPY.provisioning.flow.prompts,
        language: FLOW_COPY.provisioning.flow.language,
        preview: FLOW_COPY.provisioning.flow.preview,
      },
      governedUpdate: FLOW_COPY.provisioning.governedUpdate,
    },
    // Fatos operacionais DERIVADOS do runtime (B1) — não hard-coded no site:
    // a superfície real de comandos, a navegação curada (INTENT_CATALOG, que
    // referencia comandos por nome) e a enumeração canônica de providers/features.
    commands: siteCommandSurface(),
    decisions: siteDecisionSurface(),
    intents: INTENT_CATALOG,
    catalogs: {
      providers: getSupportedProviders(),
      features: FEATURE_OPTIONS,
    },
  };
}

export function renderSiteFlowCopyScript(): string {
  return `// ${GENERATED_NOTICE}\n// prettier-ignore\nexport const AI_GUIDELINES_FLOW_COPY = ${JSON.stringify(
    siteFlowCopyPayload(),
    null,
    2
  )} as const;\n`;
}

export function syncSiteFlowCopy(repoRoot: string): void {
  const outputPath = siteFlowCopyOutputPath(repoRoot);
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderSiteFlowCopyScript(), "utf-8");
}

export function checkSiteFlowCopy(repoRoot: string): readonly string[] {
  const outputPath = siteFlowCopyOutputPath(repoRoot);
  const expected = renderSiteFlowCopyScript();
  if (!existsSync(outputPath)) {
    return [`${OUTPUT_RELATIVE_PATH} não existe; rode npm run site:flow:sync`];
  }
  const actual = readFileSync(outputPath, "utf-8");
  if (actual !== expected) {
    return [`${OUTPUT_RELATIVE_PATH} diverge do catálogo da CLI; rode npm run site:flow:sync`];
  }
  return [];
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
  repoRoot = process.cwd(),
  logger: Logger = console
): Promise<number> {
  const command = argv[0] ?? "check";
  if (command === "sync") {
    syncSiteFlowCopy(repoRoot);
    logger.log(`✅ site:flow:sync — ${OUTPUT_RELATIVE_PATH} sincronizado com a CLI.`);
    return 0;
  }
  if (command === "check") {
    const violations = checkSiteFlowCopy(repoRoot);
    if (violations.length > 0) {
      logger.error(
        "❌ site:flow:check encontrou drift entre o site e os textos da CLI:\n" +
          violations.map((violation) => `  - ${violation}`).join("\n")
      );
      return 1;
    }
    logger.log("✅ site:flow:check — site React sincronizado com os textos da CLI.");
    return 0;
  }
  logger.error("Uso: node dist/cli/siteFlowCopy.js [check|sync]");
  return 2;
}

if (require.main === module) {
  void main().then((exitCode) => {
    if (exitCode !== 0) process.exitCode = exitCode;
  });
}
