import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { run } from "./main.js";
import { siteCommandSurface } from "./siteFlowCopy.js";

/**
 * Gerador de cenários de terminal do site (fecha B2 — "terminal não pode mentir").
 *
 * Duas classes, ambas honestas e NUNCA inventadas:
 *  - REAL: executa o runtime de verdade (`run(argv)`) em diretório temporário
 *    com `--dry-run` e captura stdout/stderr/exitCode reais. init/adopt/update
 *    têm saída determinística (caminhos relativos, sem SHAs/datas).
 *  - GUIDED: deriva as linhas do CONTRATO real do comando (description + usage
 *    do registry) para fluxos que exigem `.governance`/git/`gh` e não estabilizam
 *    em temp (work/handoff/decide/peer-review/specs). Exibido com rótulo visível
 *    "exemplo guiado" no site — não é saída literal atual, é derivado do runtime.
 *
 * O site renderiza `kind` como badge: nada parece terminal real sem ser real.
 */

const GENERATED_NOTICE = "Generated by npm run site:scenarios:sync. Do not edit manually.";
const OUTPUT_RELATIVE_PATH = "site/src/generated/flow-scenarios.generated.ts";

type Logger = Pick<typeof console, "error" | "log">;

export type ScenarioKind = "real" | "guided";

export interface FlowScenario {
  readonly id: string;
  readonly title: string;
  readonly kind: ScenarioKind;
  readonly command: string;
  readonly note: string;
  readonly exitCode: number | null;
  readonly lines: readonly string[];
}

export function siteScenariosOutputPath(repoRoot: string): string {
  return path.join(repoRoot, OUTPUT_RELATIVE_PATH);
}

interface RealSpec {
  readonly id: string;
  readonly title: string;
  readonly command: string;
  readonly note: string;
  /** argv SEM `--target` (injetado pelo runner apontando para o temp). */
  readonly argv: readonly string[];
  /** Semeia o diretório-alvo antes de rodar (ex.: package.json de repo existente). */
  readonly seed?: (targetDir: string) => void;
}

interface GuidedSpec {
  readonly id: string;
  readonly title: string;
  /** Nome do comando no registry — a derivação puxa description/usage reais. */
  readonly command: string;
  readonly note: string;
  /** Linhas editoriais adicionais (contexto humano); os fatos vêm do registry. */
  readonly context: readonly string[];
}

const REAL_SPECS: readonly RealSpec[] = [
  {
    id: "new-project",
    title: "Projeto novo — init em pasta limpa",
    command: "npx ai-guidelines init --dry-run",
    note: "Saída real do runtime em modo dry-run (nada é escrito).",
    argv: [
      "init",
      "--dry-run",
      "--name",
      "demo-app",
      "--package-manager",
      "npm",
      "--providers",
      "claude,gemini",
      "--yes",
    ],
  },
  {
    id: "existing-repo",
    title: "Repo existente — adopt conservador",
    command: "npx ai-guidelines adopt --dry-run",
    note: "Saída real: adopt preserva conteúdo e aborta conservador ao achar conflito sem --force.",
    argv: ["adopt", "--dry-run", "--providers", "claude", "--yes"],
    seed: (targetDir) => {
      writeFileSync(
        path.join(targetDir, "package.json"),
        `${JSON.stringify(
          { name: "legacy-app", version: "1.0.0", devDependencies: { standard: "^17.0.0" } },
          null,
          2
        )}\n`
      );
    },
  },
  {
    id: "governed-repo",
    title: "Repo já governado — update do baseline",
    command: "npx ai-guidelines update --dry-run",
    note: "Saída real: update reaplica runtime/templates/práticas via managed blocks (dry-run).",
    argv: ["update", "--dry-run", "--yes"],
    seed: (targetDir) => {
      writeFileSync(
        path.join(targetDir, "package.json"),
        `${JSON.stringify({ name: "governed-app", version: "2.1.0" }, null, 2)}\n`
      );
    },
  },
];

const GUIDED_SPECS: readonly GuidedSpec[] = [
  {
    id: "daily-work",
    title: "Uso diário — briefing de trabalho governado",
    command: "npm run flow -- work",
    note: "Exemplo guiado: derivado do contrato do comando. Rode no repo para o briefing real (lê .governance + git).",
    context: ["Lê estado, autorização, validações e quando parar — sem inventar fatos de PR/CI."],
  },
  {
    id: "handoff",
    title: "Retomar contexto — handoff situado",
    command: "npm run flow -- handoff",
    note: "Exemplo guiado: o handoff real projeta o estado vivo da spec (.governance) e do git.",
    context: [
      "Retomada factual, fontes, próxima ação única e ações proibidas derivadas do estado.",
    ],
  },
  {
    id: "decide",
    title: "Decisões reservadas ao humano",
    command: "npm run flow -- decide --brief-only",
    note: "Exemplo guiado: decide --brief-only mostra o briefing real e os bloqueios; não executa nada.",
    context: [
      "Ready, Human Gate e merge aparecem como decisões com evidência e bloqueios — nunca atalhos.",
    ],
  },
  {
    id: "peer-review",
    title: "Review entre pares — PR de outra pessoa",
    command: "npm run flow -- peer-review 43 --brief-only",
    note: "Exemplo guiado: peer-review real usa git/gh para abrir worktree/checkout (indisponível em sandbox).",
    context: ["Worktree separado preserva sua branch; checkout guiado exige working tree limpa."],
  },
  {
    id: "multi-spec",
    title: "Múltiplas specs — escolher a frente certa",
    command: "npm run flow -- specs",
    note: "Exemplo guiado: specs real lista o índice governado vivo de specs abertas.",
    context: ["Mostra id, branch esperada e PR; drift vira bloqueio, não suposição."],
  },
];

function captureRun(): {
  logger: { info(m: string): void; error(m: string): void };
  lines: string[];
} {
  const lines: string[] = [];
  return {
    logger: { info: (m: string) => lines.push(m), error: (m: string) => lines.push(m) },
    lines,
  };
}

/** Remove tokens dependentes do ambiente (caminhos temporários). */
function redact(line: string, targetDir: string, tmpDir: string): string {
  return line.split(targetDir).join("<target>").split(tmpDir).join("<tmp>");
}

async function buildRealScenario(spec: RealSpec): Promise<FlowScenario> {
  const tmpDir = mkdtempSync(path.join(os.tmpdir(), "aig-scenario-"));
  const targetDir = path.join(tmpDir, "repo");
  try {
    mkdirSync(targetDir, { recursive: true });
    spec.seed?.(targetDir);
    const { logger, lines } = captureRun();
    const exitCode = await run([...spec.argv, "--target", targetDir], { logger });
    return {
      id: spec.id,
      title: spec.title,
      kind: "real",
      command: spec.command,
      note: spec.note,
      exitCode,
      lines: lines
        .flatMap((line) => line.split("\n"))
        .map((line) => redact(line, targetDir, tmpDir)),
    };
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

function buildGuidedScenario(spec: GuidedSpec): FlowScenario {
  // Casa o descriptor real pelo primeiro token do comando (ex.: `decide --brief-only` → `decide`).
  const name = spec.command.replace(/^npm run flow -- /, "").split(" ")[0];
  const real = siteCommandSurface().find((command) => command.name === name);
  const lines: string[] = [];
  if (real) {
    lines.push(`# ${real.name} — ${real.description}`);
    for (const usage of real.usage) {
      lines.push(`$ npm run flow -- ${usage}`);
    }
  }
  for (const contextLine of spec.context) {
    lines.push(contextLine);
  }
  return {
    id: spec.id,
    title: spec.title,
    kind: "guided",
    command: spec.command,
    note: spec.note,
    exitCode: null,
    lines,
  };
}

export async function buildSiteScenarios(): Promise<readonly FlowScenario[]> {
  const real: FlowScenario[] = [];
  for (const spec of REAL_SPECS) {
    real.push(await buildRealScenario(spec));
  }
  const guided = GUIDED_SPECS.map(buildGuidedScenario);
  return [...real, ...guided];
}

export async function renderSiteScenariosScript(): Promise<string> {
  const scenarios = await buildSiteScenarios();
  return `// ${GENERATED_NOTICE}\n// prettier-ignore\nexport const AI_GUIDELINES_FLOW_SCENARIOS = ${JSON.stringify(
    scenarios,
    null,
    2
  )} as const;\n`;
}

export async function syncSiteScenarios(repoRoot: string): Promise<void> {
  const outputPath = siteScenariosOutputPath(repoRoot);
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, await renderSiteScenariosScript(), "utf-8");
}

export async function checkSiteScenarios(repoRoot: string): Promise<readonly string[]> {
  const outputPath = siteScenariosOutputPath(repoRoot);
  const expected = await renderSiteScenariosScript();
  if (!existsSync(outputPath)) {
    return [`${OUTPUT_RELATIVE_PATH} não existe; rode npm run site:scenarios:sync`];
  }
  const actual = readFileSync(outputPath, "utf-8");
  if (actual !== expected) {
    return [
      `${OUTPUT_RELATIVE_PATH} diverge dos transcripts do runtime; rode npm run site:scenarios:sync`,
    ];
  }
  return [];
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
  repoRoot = process.cwd(),
  logger: Logger = console
): Promise<number> {
  const command = argv[0] ?? "check";
  if (command === "sync") {
    await syncSiteScenarios(repoRoot);
    logger.log(`✅ site:scenarios:sync — ${OUTPUT_RELATIVE_PATH} gerado do runtime real.`);
    return 0;
  }
  if (command === "check") {
    const violations = await checkSiteScenarios(repoRoot);
    if (violations.length > 0) {
      logger.error(
        "❌ site:scenarios:check encontrou drift entre o site e os transcripts do runtime:\n" +
          violations.map((violation) => `  - ${violation}`).join("\n")
      );
      return 1;
    }
    logger.log("✅ site:scenarios:check — transcripts do site sincronizados com o runtime.");
    return 0;
  }
  logger.error("Uso: node dist/cli/siteScenarios.js [check|sync]");
  return 2;
}

if (require.main === module) {
  void main().then((exitCode) => {
    if (exitCode !== 0) process.exitCode = exitCode;
  });
}
