import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";

import type { ResolvedActiveSpec } from "../app/workflow/ListActiveSpecs.js";
import {
  ConfirmOptions,
  GroupedMultiSelectOptions,
  InputOptions,
  MultiSelectOptions,
  PromptStatusKind,
  PromptTask,
  Prompts,
  SelectOptions,
  SpinnerOptions,
  TaskLog,
  TaskLogOptions,
} from "../app/ports/Prompts.js";
import { FLOW_COPY } from "./copy/flowCopy.js";
import type { CockpitModel } from "./cockpit.js";
import { NodeBootstrapDeliveryRuntime } from "./delivery/bootstrap/composition.js";
import { buildBootstrapDeliveryRegistry } from "./delivery/bootstrap/registry.js";
import { deriveSuggestedOperation } from "./delivery/bootstrap/wizard.js";
import {
  detectProvisioningContext,
  type ProvisioningContextSummary,
} from "./experience/wizard/provisioning.js";
import { runFlowWizard } from "./flowWizard.js";
import type { GovernedFlowAction } from "./flow/GovernedFlow.js";
import { CommandContext, Logger as CommandLogger } from "./registry/Command.js";
import { CommandRegistry } from "./registry/CommandRegistry.js";

/**
 * Gerador da MÁQUINA DE PROMPTS real do onboarding público (`npx ai-guidelines`).
 *
 * Premissa (decisão da owner — "projeção gerada da sequência"): o simulador do
 * site não pode inventar prompt. Toda mensagem, opção e ramificação é capturada
 * por EXECUÇÃO CONTROLADA do wizard real — o mesmo `command.prompt(context)` que
 * o consumidor vê ao rodar `npx ai-guidelines`. Aqui injetamos um `Prompts`
 * GRAVADOR que, em vez de perguntar ao humano, registra cada chamada (mensagem +
 * choices reais) e devolve uma resposta roteirizada só para atravessar o fluxo.
 *
 * `command.prompt()` é prompting PURO (não toca filesystem) e devolve as options
 * sem efeito colateral — paramos antes de `run()`. O RESULTADO (o que seria
 * escrito) vem do transcript de dry-run real já capturado em
 * `flow-scenarios.generated.ts` (`transcriptId`), nunca de texto autoral.
 *
 * `npm run site:prompts:sync` regenera; `site:prompts:check` falha no drift.
 */

const GENERATED_NOTICE = "Generated by npm run site:prompts:sync. Do not edit manually.";
const OUTPUT_RELATIVE_PATH = "site/src/generated/flow-prompts.generated.ts";

const PROVISIONING_COPY = FLOW_COPY.provisioning;
const ADVANCED_MESSAGE = PROVISIONING_COPY.flow.prompts.advanced;
const CONFIRM_APPLY_MESSAGE = PROVISIONING_COPY.flow.prompts.confirmApply;
const ADVANCED_SUB_MESSAGES = new Set<string>([
  PROVISIONING_COPY.flow.prompts.runtimeDir,
  PROVISIONING_COPY.flow.prompts.forcePrettier,
  PROVISIONING_COPY.flow.prompts.prune,
]);

type Logger = Pick<typeof console, "error" | "log">;
type Operation = "init" | "adopt" | "update" | "root";

export interface PromptChoiceRecord {
  readonly label: string;
  readonly value: string;
  readonly hint?: string;
  readonly disabled?: boolean;
}

export interface PromptGroupRecord {
  readonly group: string;
  readonly choices: readonly PromptChoiceRecord[];
}

export interface PromptGate {
  readonly stepId: string;
  readonly equals: boolean;
}

export interface PromptValueGate {
  readonly stepId: string;
  readonly includes: string;
}

/**
 * Um passo da sequência. `kind` espelha o affordance real do @clack. Campos
 * opcionais aparecem só quando o tipo os usa (JSON enxuto, igual ao gerado de
 * cenários). `gatedBy` marca passos que só existem sob uma resposta anterior
 * (ramificação real: o bloco avançado só aparece se "avançado" = sim).
 */
export interface PromptStep {
  readonly kind: "note" | "input" | "select" | "multiselect" | "confirm";
  readonly id: string;
  readonly message: string;
  readonly title?: string;
  readonly lines?: readonly string[];
  readonly choices?: readonly PromptChoiceRecord[];
  readonly groups?: readonly PromptGroupRecord[];
  readonly defaultValues?: readonly string[];
  readonly required?: boolean;
  readonly defaultText?: string;
  readonly defaultBool?: boolean;
  readonly suggested?: string | readonly string[] | boolean;
  readonly gatedBy?: PromptGate;
  readonly requiresSelection?: PromptValueGate;
}

export interface PromptFlow {
  readonly id: string;
  readonly operation: Operation;
  readonly context: string;
  /** Porta pública mostrada no topo do terminal — sempre o caminho principal. */
  readonly command: string;
  readonly detection: {
    readonly title: string;
    readonly evidence: readonly string[];
    readonly formatterRival?: string;
  };
  /** Id do transcript REAL de dry-run (em flow-scenarios) usado como saída. */
  readonly transcriptId: string;
  readonly steps: readonly PromptStep[];
}

interface FlowSpec {
  readonly id: string;
  readonly operation: Operation;
  readonly context: "empty" | "existing" | "conflict" | "governed";
  readonly fixtureId: string;
  readonly transcriptId: string;
}

const FLOW_SPECS: readonly FlowSpec[] = [
  {
    id: "empty",
    operation: "init",
    context: "empty",
    fixtureId: "consumer-empty",
    transcriptId: "new-project",
  },
  {
    id: "existing",
    operation: "adopt",
    context: "existing",
    fixtureId: "consumer-existing-package",
    transcriptId: "existing-repo",
  },
  {
    id: "conflict",
    operation: "adopt",
    context: "conflict",
    fixtureId: "consumer-existing-formatter-conflict",
    transcriptId: "existing-repo",
  },
  {
    id: "governed",
    operation: "update",
    context: "governed",
    fixtureId: "consumer-governed-solo",
    transcriptId: "governed-repo",
  },
];

interface DailyFlowSpec {
  readonly id: "daily-resume" | "daily-focus" | "daily-peer";
  readonly context: "daily-resume" | "daily-focus" | "daily-peer";
  readonly fixture: "single" | "multiple" | "peer";
}

const DAILY_FLOW_SPECS: readonly DailyFlowSpec[] = [
  { id: "daily-resume", context: "daily-resume", fixture: "single" },
  { id: "daily-focus", context: "daily-focus", fixture: "multiple" },
  { id: "daily-peer", context: "daily-peer", fixture: "peer" },
];

export function sitePromptFlowsOutputPath(repoRoot: string): string {
  return path.join(repoRoot, OUTPUT_RELATIVE_PATH);
}

/**
 * `Prompts` que grava cada affordance e devolve uma resposta determinística para
 * atravessar o fluxo. As respostas existem só para chegar ao fim do wizard; o
 * que importa é o registro fiel de mensagens e opções REAIS.
 */
class RecordingPrompts implements Prompts {
  readonly steps: PromptStep[] = [];
  private counter = 0;

  constructor(private readonly selectOverrides: Readonly<Record<string, string>> = {}) {}

  private nextId(kind: string): string {
    this.counter += 1;
    return `${kind}-${this.counter}`;
  }

  async select<T = string>(options: SelectOptions<T>): Promise<T> {
    const choices = options.choices.map(toChoiceRecord);
    const override = this.selectOverrides[options.message];
    const suggested = override ?? choices[0]?.value ?? "";
    this.steps.push({
      kind: "select",
      id: this.nextId("select"),
      message: options.message,
      choices,
      suggested,
    });
    return (options.choices.find((choice) => String(choice.value) === suggested)?.value ??
      options.choices[0]?.value) as T;
  }

  async multiselect<T = string>(options: MultiSelectOptions<T>): Promise<readonly T[]> {
    return this.recordMultiselect(
      options.message,
      [{ group: "", choices: options.choices.map(toChoiceRecord) }],
      options.defaultValues,
      options.required ?? false,
      options.choices.map((choice) => choice.value)
    );
  }

  async groupMultiselect<T = string>(options: GroupedMultiSelectOptions<T>): Promise<readonly T[]> {
    const groups: PromptGroupRecord[] = Object.entries(options.groups).map(([group, choices]) => ({
      group,
      choices: choices.map(toChoiceRecord),
    }));
    const allValues = Object.values(options.groups).flatMap((choices) =>
      choices.map((choice) => choice.value)
    );
    return this.recordMultiselect(
      options.message,
      groups,
      options.defaultValues,
      options.required ?? false,
      allValues
    );
  }

  private recordMultiselect<T>(
    message: string,
    groups: readonly PromptGroupRecord[],
    defaultValues: readonly T[] | undefined,
    required: boolean,
    allValues: readonly T[]
  ): readonly T[] {
    const answer = defaultValues ?? allValues;
    this.steps.push({
      kind: "multiselect",
      id: this.nextId("multiselect"),
      message,
      groups,
      defaultValues: answer.map(String),
      required,
      suggested: answer.map(String),
    });
    return answer;
  }

  async input(options: InputOptions): Promise<string> {
    const fallback = options.default ?? "";
    this.steps.push({
      kind: "input",
      id: this.nextId("input"),
      message: options.message,
      defaultText: fallback,
      suggested: fallback,
    });
    return fallback;
  }

  async confirm(options: ConfirmOptions): Promise<boolean> {
    const answer =
      options.message === ADVANCED_MESSAGE || options.message === CONFIRM_APPLY_MESSAGE
        ? true
        : (options.default ?? false);
    this.steps.push({
      kind: "confirm",
      id: this.nextId("confirm"),
      message: options.message,
      defaultBool: options.default ?? false,
      suggested: answer,
    });
    return answer;
  }

  async note(message: string, title?: string): Promise<void> {
    this.steps.push({
      kind: "note",
      id: this.nextId("note"),
      message: title ?? "",
      ...(title ? { title } : {}),
      lines: message.split("\n"),
    });
  }

  async box(message: string, title?: string): Promise<void> {
    await this.note(message, title);
  }

  // Affordances de saída/feedback não geram passo de PROMPT no simulador.
  async intro(): Promise<void> {}
  async outro(): Promise<void> {}
  async cancel(): Promise<void> {}
  async status(_kind: PromptStatusKind, _message: string): Promise<void> {}

  async spinner<T = void>(options: SpinnerOptions<T>): Promise<T> {
    return options.task();
  }

  async taskList(tasks: readonly PromptTask[]): Promise<void> {
    for (const task of tasks) {
      await task.task(() => {});
    }
  }

  taskLog(_options: TaskLogOptions): TaskLog {
    const group = {
      message: () => {},
      success: () => {},
      error: () => {},
    };
    return {
      message: () => {},
      group: () => group,
      success: () => {},
      error: () => {},
    };
  }
}

function toChoiceRecord<T>(choice: {
  readonly name: string;
  readonly value: T;
  readonly hint?: string;
  readonly disabled?: boolean;
}): PromptChoiceRecord {
  return {
    label: choice.name,
    value: String(choice.value),
    ...(choice.hint !== undefined ? { hint: choice.hint } : {}),
    ...(choice.disabled !== undefined ? { disabled: choice.disabled } : {}),
  };
}

interface WizardCommand {
  readonly name: string;
  readonly wizard: { readonly enabled: boolean; readonly label: string };
  prompt?(context: CommandContext): Promise<unknown>;
}

function wizardCommands(registry: CommandRegistry): readonly WizardCommand[] {
  const result: WizardCommand[] = [];
  for (const command of registry.commands()) {
    const candidate = command as unknown as Partial<WizardCommand>;
    if (
      typeof candidate.wizard?.enabled === "boolean" &&
      candidate.wizard.enabled &&
      typeof candidate.prompt === "function"
    ) {
      result.push(candidate as WizardCommand);
    }
  }
  return result;
}

function buildOperationStep(registry: CommandRegistry, suggested: Operation): PromptStep {
  const commands = wizardCommands(registry);
  const ordered = [
    ...commands.filter((command) => command.name === suggested),
    ...commands.filter((command) => command.name !== suggested),
  ];
  return {
    // "Operation" é a mensagem literal do BootstrapWizard real (wizard.ts).
    kind: "select",
    id: "operation",
    message: "Operation",
    choices: ordered.map((command) => ({ label: command.wizard.label, value: command.name })),
    suggested,
  };
}

function buildDetectionStep(summary: ProvisioningContextSummary): PromptStep {
  return {
    kind: "note",
    id: "detection",
    message: summary.stateTitle,
    title: summary.stateTitle,
    lines: [
      PROVISIONING_COPY.section.detectedLabel,
      ...summary.evidence.map((item) => `- ${item}`),
    ],
  };
}

function applyAdvancedGate(steps: readonly PromptStep[]): readonly PromptStep[] {
  const advanced = steps.find(
    (step) => step.kind === "confirm" && step.message === ADVANCED_MESSAGE
  );
  if (!advanced) return steps;
  const features = steps.find(
    (step) =>
      step.kind === "multiselect" && step.message === PROVISIONING_COPY.featureInstallQuestion
  );
  return steps.map((step) =>
    ADVANCED_SUB_MESSAGES.has(step.message)
      ? {
          ...step,
          gatedBy: { stepId: advanced.id, equals: true },
          ...(step.message === PROVISIONING_COPY.flow.prompts.forcePrettier && features
            ? { requiresSelection: { stepId: features.id, includes: "prettier" } }
            : {}),
        }
      : step
  );
}

function seedFixture(repoRoot: string, fixtureId: string, targetDir: string): void {
  const fixtureFiles = path.join(
    repoRoot,
    "tests",
    "consumer-journey",
    "fixtures",
    fixtureId,
    "files"
  );
  if (existsSync(fixtureFiles)) {
    cpSync(fixtureFiles, targetDir, { recursive: true });
  }
}

function detectFromFixture(repoRoot: string, fixtureId: string): ProvisioningContextSummary {
  const tmpDir = mkdtempSync(path.join(os.tmpdir(), "aig-prompts-"));
  const targetDir = path.join(tmpDir, "repo");
  try {
    mkdirSync(targetDir, { recursive: true });
    seedFixture(repoRoot, fixtureId, targetDir);
    return detectProvisioningContext(targetDir);
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

function writeDailyGovernedRepo(targetDir: string, specCount: 1 | 3): void {
  writeFileSync(
    path.join(targetDir, "package.json"),
    `${JSON.stringify({ name: "consumer-governed-demo", version: "0.0.1", private: true }, null, 2)}\n`
  );
  mkdirSync(path.join(targetDir, ".ai-guidelines"), { recursive: true });
  writeFileSync(
    path.join(targetDir, ".ai-guidelines", "config.json"),
    `${JSON.stringify(
      {
        version: 1,
        project: { name: "consumer-governed-demo", packageManager: "npm" },
        providers: ["claude"],
        features: [],
        lang: "pt",
      },
      null,
      2
    )}\n`
  );
  mkdirSync(path.join(targetDir, ".governance", "runtime", "specs"), { recursive: true });
  mkdirSync(path.join(targetDir, ".governance", "specs"), { recursive: true });
  writeFileSync(
    path.join(targetDir, ".governance", "review-policy.yml"),
    [
      "active_profile: solo",
      "profiles:",
      "  solo:",
      "    implementation_pr:",
      "      required_native_approvals: 0",
      "    integration_pr:",
      "      required_native_approvals: 0",
      "",
    ].join("\n")
  );
  writeFileSync(
    path.join(targetDir, ".governance", "runtime", "specs", "active.yml"),
    dailyActiveSpecsYaml(specCount)
  );

  const specs =
    specCount === 1 ? ["0024-demo"] : ["0024-co-flow", "0025-docs", "0026-housekeeping"];
  for (const spec of specs) {
    const specDir = path.join(targetDir, ".governance", "specs", spec);
    mkdirSync(specDir, { recursive: true });
    writeFileSync(
      path.join(specDir, "state.yml"),
      [
        "stage: implementation",
        "topology:",
        "  cursor:",
        `    pr: ${spec.replace(/^\d+-/, "")}`,
        `    checkpoint: checkpoint-${spec.replace(/^\d+-/, "")}`,
        "",
      ].join("\n")
    );
  }
}

function dailyActiveSpecsYaml(specCount: 1 | 3): string {
  const entries =
    specCount === 1
      ? [activeSpecYaml("0024", "demo", "Spec Demo", "feat/spec-0024-demo")]
      : [
          activeSpecYaml("0024", "co-flow", "Co-flow convergence", "feat/spec-0024-co-flow"),
          activeSpecYaml("0025", "docs", "Documentacao publica", "feat/spec-0025-docs"),
          activeSpecYaml("0026", "housekeeping", "Housekeeping", "feat/spec-0026-housekeeping"),
        ];
  return ["version: 1", "active_specs:", ...entries].join("\n");
}

function activeSpecYaml(id: string, slug: string, title: string, branch: string): string {
  const folder = `${id}-${slug}`;
  return [
    `  - id: "${id}"`,
    `    slug: ${slug}`,
    `    title: ${title}`,
    `    branch: ${branch}`,
    "    stage: implementation",
    "    status: active",
    `    spec_path: .governance/specs/${folder}`,
    `    source_state_path: .governance/specs/${folder}/state.yml`,
    "    updated_at: 2026-06-19T00:00:00-03:00",
    '    updated_by: "@consumer"',
  ].join("\n");
}

function resolvedActiveSpec(
  id: string,
  slug: string,
  title: string,
  branch: string
): ResolvedActiveSpec {
  return {
    entry: {
      id,
      slug,
      title,
      branch,
      stage: "implementation",
      status: "active",
      specPath: `.governance/specs/${id}-${slug}`,
      sourceStatePath: `.governance/specs/${id}-${slug}/state.yml`,
      updatedAt: "2026-06-19T00:00:00-03:00",
      updatedBy: "@consumer",
    },
    specPathExists: true,
  };
}

function dailySpecsResult(fixture: DailyFlowSpec["fixture"]): {
  readonly indexAvailable: true;
  readonly entries: readonly ResolvedActiveSpec[];
  readonly warnings: readonly string[];
} {
  if (fixture === "multiple") {
    return {
      indexAvailable: true,
      entries: [
        resolvedActiveSpec("0024", "co-flow", "Co-flow convergence", "feat/spec-0024-co-flow"),
        resolvedActiveSpec("0025", "docs", "Documentacao publica", "feat/spec-0025-docs"),
        resolvedActiveSpec("0026", "housekeeping", "Housekeeping", "feat/spec-0026-housekeeping"),
      ],
      warnings: [],
    };
  }
  return {
    indexAvailable: true,
    entries: [resolvedActiveSpec("0024", "demo", "Spec Demo", "feat/spec-0024-demo")],
    warnings: [],
  };
}

function dailyAction(title: string, command: string): GovernedFlowAction {
  return {
    id: "finish-step",
    title,
    availability: { status: "available", reasons: [] },
    command,
    effect: ["somente orienta a próxima ação neste simulador"],
  };
}

function dailyCockpitModel(spec: DailyFlowSpec): CockpitModel {
  const branch = spec.fixture === "multiple" ? "feat/spec-0024-co-flow" : "feat/spec-0024-demo";
  const specLabel = spec.fixture === "multiple" ? "0024-co-flow" : "0024-demo";
  const lifecycle = {
    openFindings: spec.fixture === "peer" ? 1 : 0,
    openBlocking: 0,
    closedFindings: spec.fixture === "peer" ? 2 : 0,
    resolutions: spec.fixture === "peer" ? 1 : 0,
    reviewStatuses: [] as readonly {
      readonly typeId: string;
      readonly state: string;
      readonly blocking: boolean;
    }[],
  };
  const facts = {
    git: { branch, head: "abc1234", behind: 0 },
    spec: { label: specLabel },
    pullRequest: {
      number: spec.fixture === "multiple" ? 143 : 101,
      state: "open",
      isDraft: true,
      checks: { pass: 3, fail: 0, pending: 0 },
    },
    lifecycle,
    sources: [{ status: "fresh" }],
  };
  const nextAction =
    spec.fixture === "multiple"
      ? "Escolher a frente certa antes de continuar."
      : spec.fixture === "peer"
        ? "Preparar review isolado de PR de colega."
        : "Retomar o contexto e ver a próxima ação segura.";
  const command =
    spec.fixture === "multiple"
      ? "npx ai-guidelines specs"
      : spec.fixture === "peer"
        ? "npx ai-guidelines peer-review <pr>"
        : "npx ai-guidelines work";
  const recommended =
    spec.fixture === "multiple" || spec.fixture === "peer"
      ? null
      : dailyAction(nextAction, command);

  return {
    work: {
      snapshot: {
        collected: { facts },
      } as never,
      brief: {
        specId: specLabel,
        checkpoint: `checkpoint-${specLabel}`,
        gitHead: "abc1234",
        effectiveFunctionalHead: "abc1234",
        workingTreeState: "clean",
        mode: "implement_checkpoint",
        purpose: "Simular uso diario em repo governado.",
        modeBasis: [],
        degraded: [],
        object: {
          step: { id: "DEMO-1", title: "trabalho em andamento", line: 1 },
        },
        authorization: { granted: false, reason: "site simulator" },
        allowedActions: [],
        forbiddenActions: [],
        validations: [],
        publication: { commit: false, push: false },
        expectsResolutions: false,
        prBodyEditable: false,
        stopConditions: [],
        reportSections: [],
        nextAction: {
          description: nextAction,
          basis: [],
          commands: [{ label: "atalho", command }],
          stillForbidden: [],
          decisionType: null,
        },
      } as never,
    },
    decisions: [],
    flow: {
      actions: recommended ? [recommended] : [],
      available: recommended ? [recommended] : [],
      blocked: [
        {
          id: "human-gate",
          title: "Decidir Human Gate",
          availability: { status: "blocked", reasons: ["O PR ainda esta em Draft."] },
          command: "npx ai-guidelines decide --type human-gate --brief-only",
          effect: [],
        },
      ],
      forbidden: ["Fazer merge", "Executar Human Gate sem decisão humana explícita"],
      recommended,
      humanSummary: {
        state: [
          "Repo governado detectado.",
          spec.fixture === "multiple"
            ? "Ha mais de uma spec ativa; escolha o foco antes de decidir."
            : "Ha uma spec ativa em andamento.",
          "Working tree limpa.",
        ],
        currentObject: {
          label: spec.fixture === "multiple" ? "Várias specs ativas" : "Spec ativa",
          objective: nextAction,
          output: null,
        },
        nextObject: null,
        ready: ["O repo ja usa ai-guidelines.", "O contexto local foi carregado."],
        missing:
          spec.fixture === "multiple"
            ? ["Falta escolher qual spec recebera atenção agora."]
            : ["Falta escolher a ação da sessão."],
        nextAction,
        command,
        forbidden: ["Human Gate", "merge"],
      },
    },
  };
}

function buildDailyDetectionStep(summary: ProvisioningContextSummary): PromptStep {
  return {
    kind: "note",
    id: "daily-detection",
    message: summary.stateTitle,
    title: summary.stateTitle,
    lines: [
      PROVISIONING_COPY.section.detectedLabel,
      ...summary.evidence.map((item) => `- ${item}`),
    ],
  };
}

async function buildDailyFlow(spec: DailyFlowSpec, registry: CommandRegistry): Promise<PromptFlow> {
  const tmpDir = mkdtempSync(path.join(os.tmpdir(), "aig-daily-prompts-"));
  const targetDir = path.join(tmpDir, "repo");
  try {
    mkdirSync(targetDir, { recursive: true });
    writeDailyGovernedRepo(targetDir, spec.fixture === "multiple" ? 3 : 1);
    const detected = detectProvisioningContext(targetDir);
    const recorder = new RecordingPrompts({ [FLOW_COPY.wizard.mainQuestion]: "quit" });
    const logger: CommandLogger = { info: () => {}, error: () => {} };
    await runFlowWizard(targetDir, logger, {
      prompts: recorder,
      registry,
      collectModel: () => dailyCockpitModel(spec),
      loadActiveSpecsIndex: () => dailySpecsResult(spec.fixture),
    });

    return {
      id: spec.id,
      operation: "root",
      context: spec.context,
      command: "npx ai-guidelines",
      detection: {
        title: detected.stateTitle,
        evidence: [...detected.evidence],
      },
      transcriptId: spec.id,
      steps: [buildDailyDetectionStep(detected), ...recorder.steps],
    };
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

async function buildFlow(spec: FlowSpec, registry: CommandRegistry): Promise<PromptFlow> {
  const detected = detectFromFixture(process.cwd(), spec.fixtureId);
  const suggested = deriveSuggestedOperation({
    configExists: detected.workspaceShape === "governed-repo",
    packageJsonExists: detected.workspaceShape === "package-repo",
  });

  const command = wizardCommands(registry).find((entry) => entry.name === spec.operation);
  if (!command?.prompt) {
    throw new Error(`sitePromptFlows: comando "${spec.operation}" não expõe prompt no registry.`);
  }

  const recorder = new RecordingPrompts();
  const logger: CommandLogger = { info: () => {}, error: () => {} };
  await command.prompt({ repoRoot: process.cwd(), logger, prompts: recorder });

  const steps = applyAdvancedGate([
    buildDetectionStep(detected),
    buildOperationStep(registry, suggested),
    ...recorder.steps,
  ]);

  return {
    id: spec.id,
    operation: spec.operation,
    context: spec.context,
    command: "npx ai-guidelines",
    detection: {
      title: detected.stateTitle,
      evidence: [...detected.evidence],
      ...(detected.formatterRivalLabel ? { formatterRival: detected.formatterRivalLabel } : {}),
    },
    transcriptId: spec.transcriptId,
    steps,
  };
}

export async function buildSitePromptFlows(
  repoRoot: string = process.cwd()
): Promise<readonly PromptFlow[]> {
  const runtime = new NodeBootstrapDeliveryRuntime(repoRoot);
  const registry = buildBootstrapDeliveryRegistry(runtime);
  const flows: PromptFlow[] = [];
  for (const spec of FLOW_SPECS) {
    flows.push(await buildFlow(spec, registry));
  }
  for (const spec of DAILY_FLOW_SPECS) {
    flows.push(await buildDailyFlow(spec, registry));
  }
  return flows;
}

export async function renderSitePromptFlowsScript(
  repoRoot: string = process.cwd()
): Promise<string> {
  const scenarios = await buildSitePromptFlows(repoRoot);
  return `// ${GENERATED_NOTICE}\n// prettier-ignore\nexport const AI_GUIDELINES_FLOW_PROMPTS = ${JSON.stringify(
    { scenarios },
    null,
    2
  )} as const;\n`;
}

export async function syncSitePromptFlows(repoRoot: string): Promise<void> {
  const outputPath = sitePromptFlowsOutputPath(repoRoot);
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, await renderSitePromptFlowsScript(repoRoot), "utf-8");
}

export async function checkSitePromptFlows(repoRoot: string): Promise<readonly string[]> {
  const outputPath = sitePromptFlowsOutputPath(repoRoot);
  const expected = await renderSitePromptFlowsScript(repoRoot);
  if (!existsSync(outputPath)) {
    return [`${OUTPUT_RELATIVE_PATH} não existe; rode npm run site:prompts:sync`];
  }
  const actual = readFileSync(outputPath, "utf-8");
  if (actual !== expected) {
    return [
      `${OUTPUT_RELATIVE_PATH} diverge da máquina de prompts do runtime; rode npm run site:prompts:sync`,
    ];
  }
  return [];
}

export async function main(
  argv: readonly string[] = process.argv.slice(2),
  repoRoot = process.cwd(),
  logger: Logger = console
): Promise<number> {
  const command = argv[0] ?? "check";
  if (command === "sync") {
    await syncSitePromptFlows(repoRoot);
    logger.log(`✅ site:prompts:sync — ${OUTPUT_RELATIVE_PATH} gerado do wizard real.`);
    return 0;
  }
  if (command === "check") {
    const violations = await checkSitePromptFlows(repoRoot);
    if (violations.length > 0) {
      logger.error(
        "❌ site:prompts:check encontrou drift entre o site e a máquina de prompts do runtime:\n" +
          violations.map((violation) => `  - ${violation}`).join("\n")
      );
      return 1;
    }
    logger.log("✅ site:prompts:check — máquina de prompts do site sincronizada com o runtime.");
    return 0;
  }
  logger.error("Uso: node dist/cli/sitePromptFlows.js [check|sync]");
  return 2;
}

if (require.main === module) {
  void main().then((exitCode) => {
    if (exitCode !== 0) process.exitCode = exitCode;
  });
}
